endlessm/kolibri-explore-plugin

kolibri_explore_plugin/assets/src/views/Base.vue, kolibri_explore_plugin/assets/src/views/ChannelsPage.vue, kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue, kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
This patch adds a new component to use as base for all explore views.
This component adds the sidebar and one FAB button to show the sidebar.
Inside the custom presentation this will show just a close button to go
back to the channel list.
https://phabricator.endlessm.com/T31231
=> Add custom Base component

MANIFEST.in
On [this commit](https://github.com/endlessm/kolibri-explore-plugin/commit/f2a88b23c97ca82706b3d9efb64ccaf5f5bccdde) I forgot to add the `jpg` files to the whl package.
=> Add app jpg background files to the whl package

.yarnrc
The github workflow check usually fails to download the
material-design-icons tarball with a timeout. Let's see
if 10 minutes is enough.
https://phabricator.endlessm.com/T31344
=> Set yarn timeout to 10 minutes

kolibri_explore_plugin/kolibri_plugin.py
This plugin will override the learn plugin functionality so we can use
the same url so other tools that does redirects will continue working
when this plugin is enabled.
https://phabricator.endlessm.com/T31247
=> Use the same url as the learn plugin

kolibri_explore_plugin/urls.py
The cache is done by the browser and even with a fresh built endless
key, the cache in the browser is used to render.
This patch removes the cache_forever and adds a never_cache to avoid
browser caching.
In the future we can think about using the version number in urls to be
able to use the cache_forever, but for now this will fix the known
issues.
https://phabricator.endlessm.com/T31425
=> Avoid cache in AppView

tox.ini
From the github-actions configuration.
https://phabricator.endlessm.com/T31414
=> CI tool: Remove hardcoded version

README.md, kolibri_explore_plugin/urls.py, kolibri_explore_plugin/views.py
This patch adds a new view that just is a proxy to localhost:8080. This
proxy is used to replace the custom channel presentation zip bundle so
we can preview the result with the custom channel presentation dev
server.
The PROXY_CUSTOM_CHANNEL environ variable should be set on the kolibri
django command environment.
https://phabricator.endlessm.com/T31513
=> Proxy custom channel for development

kolibri_explore_plugin/assets/src/components/Carousel.vue
This component used the bootstrap <b-carousel> component to show a
carousel that links directly to content.
This is an example of use:
<Carousel
width="1440"
hegith="368"
interval="5000"
:slides="slides"
/>
Slides should be a list of objects with the following parameters:
* image (required) Link to the image to show
* content (required) Id of the content to link to
* caption (optional) Title to show in the slide
* text (optional) Text to show in the slide
const slides = [
{
caption: 'Example content',
image: 'https://picsum.photos/1440/368/?image=54',
content: '4adb51edf0e75de6be1c81be58e27a0d',
},
...
];
https://phabricator.endlessm.com/T31544
=> Demo: Add Carousel component

kolibri_explore_plugin/assets/src/components/Header.vue, kolibri_explore_plugin/assets/src/views/Base.vue, kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
This new header component has the endless logo and two links, one for
the home and another fake link with the text "Learn".
The search input has been moved to this new component.
The base component has been updated to remove the SideNav component so
there's no way to see the kolibri sidenav inside the plugin.
https://phabricator.endlessm.com/T31548
=> Demo: Add header component

kolibri_explore_plugin/assets/src/components/TagRow.vue
This patch implements the animation using css transformation instead of vue javascript code and margin. I don't know if this is better than the other option, but I had something similar in the past and I just want to share this solution.
This is not perfect right now. There's a small problem with the offset cards that aren't there until the end of the animation so this is not really smooth, but could be a quick solution for the demo if the other animation takes more time.
@manuq, take a look and decide if you like this or if you want to go ahead with the other implementation. Don't hesitate to ignore this if you've a clear idea of the animation, this is just a suggestion PR.
https://phabricator.endlessm.com/T31545
=> Demo: Animate tagrow with transform

README.md
- Added a paragraph of what is this plugin about
- Moved Usage and Building to the top.
- Moved Bundling apps to Building.
- Removed references to pipenv in Building, and specified version node
and yarn.
- Mention early in proxy presentation that it takes over all channels.
- Simplified Development section and divided it in:
```
```
https://phabricator.endlessm.com/T31608
=> README: Overall improvements

docker/Dockerfile, docker/Dockerfile-master, docker/entrypoint.sh
This PR adds the populate script to the docker image and tries to populate the initial content in the `entrypoint` if it was not populated before. After the population it creates the file `$KOLIBRI_HOME/populated`. If this file exists, the content is not populated, this way we only populate the content once.
https://phabricator.endlessm.com/T31632
=> docker: Add populate script to master image

kolibri_explore_plugin/assets/src/views/ContentPage.vue
Just display them for now. This will change once we have a lightbox
with the content. Then the tags should be displayed by the custom
presentation.
https://phabricator.endlessm.com/T31711
=> ContentPage: Display tags

kolibri_explore_plugin/assets/src/views/ContentItem.vue, kolibri_explore_plugin/assets/src/views/ContentLightbox.vue, kolibri_explore_plugin/assets/src/views/CustomChannelsPage.vue
This change moves the body part of ContentLightbox into a ContentItem component, as in upstream Kolibri, so we can think about the lightbox independently. I'm tweaking the modal to put a close button alongside the title using the existing UiToolbar component. This isn't _perfect_ (we need to add some extra CSS for UiToolbar to behave itself and it doesn't expect to have an arbitrarily long title). But it feels like a step in the right direction.
https://phabricator.endlessm.com/T31882
=> ContentLightbox: Add Close button

kolibri_explore_plugin/assets/src/views/ContentLightbox.vue
Done hardcoding color codes for now, maintaining the defaults from
vuex.  Because this will be migrated soon to Bootstrap theme anyways.
https://phabricator.endlessm.com/T32023
=> Discovery page: Don't use branding colors in lightbox

packages/template-ui/src/App.vue
The route to a topic was already implemented, but it was broken
because the routes changed. Also, add route to content. If both are
given, content takes precedence.
https://phabricator.endlessm.com/T31936
=> template: Route to a specific content or topic

packages/template-ui/src/components/Breadcrumb.vue
And from any other view that is not Home and that has the default root
node in vuex.
This also fixes the check for ancestors in the breadcum. The v-if
conditional was always true because even the root node has an empty
array of ancestors.
https://phabricator.endlessm.com/T31949
=> template: Add breadcum to go home from search

kolibri_explore_plugin/assets/src/modules/coreExplore/mutations.js, kolibri_explore_plugin/assets/src/modules/pluginModule.js, kolibri_explore_plugin/assets/src/routes/index.js, kolibri_explore_plugin/assets/src/views/ChannelsPage.vue, kolibri_explore_plugin/assets/src/views/SearchPage.vue
This patch adds five buttons to the discovery page header bar with
predefined search terms, clicking on that button it will open the search
page with that query and will show the results.
https://phabricator.endlessm.com/T31940
=> Discovery: Add main buttons

packages/eos-components/src/components/ContentLink.vue, packages/eos-components/src/components/PlayButton.vue, packages/template-ui/src/components/ContentImage.vue
Prevent bubbling the click event of PlayButtons using the @click.stop
modifier.
Also, use a click event handler instead of the `:to` in the
ContentLink, which is actually rendered as a
`<router-link>`. Otherwise the event is not stopped.
https://phabricator.endlessm.com/T32063
=> components: Prevent bubbling click of PlayButtons

packages/template-ui/src/components/ContentImage.vue
Instead, center the `b-img` horizontally.
https://phabricator.endlessm.com/T32073
=> template: Don't resize thumbnails in content detail view

kolibri_explore_plugin/assets/src/views/SearchPage.vue
The query attribute should be an string always.
https://phabricator.endlessm.com/T31938
=> Discovery: Fix search page without searchTerm

channel-overrides.scss, packages/eos-components/src/overrides/styles.scss, packages/eos-components/src/styles.scss, packages/eos-components/vue.config.js, packages/template-ui/vue.config.js
This is hacky because the path is pointing to another package. But the
template is doing the same to load the eos-components dynamically.
https://phabricator.endlessm.com/T32016
=> components: Load style overrides

kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue
One pixel is enough to remove the double scrollbar. Ideally we should
find why this negative margin is needed, but we are not there yet.
https://phabricator.endlessm.com/T32139
=> Discovery page: Add more negative margin to the iframe

scripts/check_can_relese.sh
The yarn bump-version command creates a tag with -a so a new object is
created, so the command:
git ls-remote https://github.com/endlessm/kolibri-explore-plugin.git $TAG
Returns the hash of the new tag object and not the head that we want. To
do it correctly we should query the $TAG^{} that resolves to the real
commit pointed by the tag, not to the tag object.
https://phabricator.endlessm.com/T32041
=> scripts: Check the TAG release not the TAG commit

kolibri_explore_plugin/assets/src/views/ChannelsPage.vue, kolibri_explore_plugin/assets/src/views/SearchPage.vue, packages/eos-components/src/components/SlidableCardGrid.vue, packages/eos-components/src/components/mixins/responsiveMixin.js, packages/eos-components/src/main.js, packages/eos-components/src/styles.scss
This patch makes the discovery page card grid and search grids
responsive, showing three cards for large screens, two for small and
one for really small screens.
A new mixin was introduced to calculate the column width and also to
change the width data in the component on resize, so it can be used to
change inside components properties.
The bootstrap sass breakpoints are also exposed in the styles.scss so it
can be used inside the javascript to determine at witch point to change
the number of elements to show.
https://phabricator.endlessm.com/T32160
=> Discovery: Make card grid responsive

packages/eos-components/src/components/ChannelLogo.vue, packages/template-ui/src/components/ChannelHeader.vue, packages/template-ui/src/components/mixins/headerMixin.js
Some improvements in the ChannelHeader logo to work correctly in different screen sizes.
In this PR the ChannelHeader uses the bootstrap col sizes to resize depending on the windows size. The channel logo is also reduced when the screen is smaller and also the title uses the `h3` class for small screens.
https://phabricator.endlessm.com/T32102
=> Template: Make ChannelHeader responsive

packages/template-ui/src/views/Section.vue
This change was introduced as part of the PR #130:
https://github.com/endlessm/kolibri-explore-plugin/pull/130/files#diff-188f7b897a1e20b9d5f7891fe048bc8b7868578210d30dbc5d7600575edf7199R26-R31
And the lint CI didn't complain there, but I'm getting some errors when
trying to run the development instance about "no-else-return":
https://eslint.org/docs/rules/no-else-return
This patch just fixes that issue and also adds the trailing `;` to the
two "return" lines.
https://phabricator.endlessm.com/T31752
=> template: Fix lint error on Section

packages/template-ui/src/components/Breadcrumb.vue, packages/template-ui/src/components/ChannelNavBar.vue
- Show only the last parent for XS and SM breakpoints.
- Hide channel logo for XS breakpoint.
Also:
- Move the "notAtHome" conditional to the navbar.
- Remove commented style.
https://phabricator.endlessm.com/T32096
=> template: Make navbar breadcrumb responsive

packages/eos-components/src/mixins.scss, packages/eos-components/src/styles.scss, packages/template-ui/src/components/ChannelHeader.vue, packages/template-ui/src/components/ChannelNavBar.vue
The header has to have a fixed height for this to work.
For smaller screens, the logic changes to stretch the center part of
the background.
https://phabricator.endlessm.com/T32175
=> template: Make navbar and header backgrounds match

packages/eos-components/src/components/CardGrid.vue, packages/template-ui/channel-overrides/pbs-kids/options.json, packages/template-ui/src/components/SectionsSearchRow.vue, packages/template-ui/src/store/index.js, packages/template-ui/src/views/Home.vue
The elements that can be removed by the overrides are:
- The row with main sections and search button.
- The carousel.
- The filter row.
Also, make the PBS-Kids override use all of them.
Also, improve the margins and replace divs with templates so the
margins count.
https://phabricator.endlessm.com/T31752
=> template: Add options to remove elements from home view

packages/eos-components/src/components/CarouselCard.vue, packages/eos-components/src/styles.scss
This property is not supported in old browsers. This patch replaces the
min property with breakpoint styles, so it's 50% for xs, sm and md and
400px for the rest.
https://phabricator.endlessm.com/T32184
=> Components: Do not use css min property

kolibri_explore_plugin/assets/src/views/ContentItem.vue
The header bar with the fullscreen icon is not inside an iframe, so
our CSS affects it. This is a workaround to compensate the offset.
https://phabricator.endlessm.com/T32186
=> Discovery page: Fix offset in html5_viewer icon

packages/template-ui/src/components/ContentImage.vue, packages/template-ui/src/views/BundleSection.vue
Add a nested grid to display 2 content images per row in medium size
screens and above. In small screens it all is piled vertically.
Make the content images "fluid" so they adjust to the container space.
Use the gutter width variable (defaults to 30px) for the bottom
margin, to have the same gutter between rows than between columns.
https://phabricator.endlessm.com/T32075
=> template: Add grid for simple bundle page

packages/eos-components/package.json, packages/eos-components/src/components/CardGridPlaceholder.vue, packages/eos-components/src/components/CarouselPlaceholder.vue, yarn.lock
This patch removes the placeholder-loading dependency and uses the
bootstrap-vue skeleton component to do that.
https://phabricator.endlessm.com/T32183
=> Components: Remove placeholder-loading dependency

packages/eos-components/src/styles.scss
These style variables overrides are not needed anymore because it was
only for the placeholder-loading module.
https://phabricator.endlessm.com/T32183
=> components: cleanup placeholder leftover styles

kolibri_explore_plugin/assets/src/views/ContentModal.vue, packages/eos-components/src/styles.scss
The existing border override needs `!important` to apply in all cases.
https://phabricator.endlessm.com/T32185
=> Remove close button shadow and white border for videos

kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue
To avoid the loading screen to be shown forever, this patch adds the
'load' signal emission before destroy the component, so if the component
is destroyed before the 'load' signal is emitted, the loading screen
will be hidden anyway.
https://phabricator.endlessm.com/T32210
=> Discovery: Hide loading screen beforeDestroy

packages/eos-components/src/mixins.scss, packages/eos-components/src/styles.scss
Use the LG breakpoint (down md) and assume that background assets will
have 2.8444 aspect ratio. Same AR as the header at exactly the LG
breakpoint. So the header height is adjusted as well.
- Below LG: the background is displayed full height.
- LG and up: the background is displayed full width.
Also, remove the unused xxl breakpoint.
https://phabricator.endlessm.com/T32175
=> template: Improve backgrounds again

kolibri_explore_plugin/assets/src/customApps.js, kolibri_explore_plugin/assets/src/views/ContentItem.vue
Add a GameAppIDs array constant to store all the channels that need
the fullscreen bar removed. For now it's just the Terminal Two
channel.
Use the array to add a CSS class to the content renderer, and add a
display: hidden rule to it.
https://phabricator.endlessm.com/T32242
=> content renderer: Remove fullscreen bar for T2 games

kolibri_explore_plugin/assets/src/views/ContentItem.vue, kolibri_explore_plugin/assets/src/views/ContentModal.vue
This pull request corrects some small errors in content toolbars:
- Icon buttons in a dark styled toolbar (the "+" and "-" buttons in the document viewer) have their colours set accordingly.
- Full-screen button icons are sized consistently (and vertically aligned with their text).
https://phabricator.endlessm.com/T32187
=> T32187 fullscreen icon tweaks

packages/eos-components/src/components/mixins/cardMixin.js
This patch fixes a regression introduced in the following commit:
https://github.com/endlessm/kolibri-explore-plugin/commit/beb2a48d375d0a5fc902e4068b8e35c82d655e4c
It shows the default thumbnail always in custom channels. This patch
fixes that in brings back the content thumbnail async load.
https://phabricator.endlessm.com/T32077
=> Components: Fix thumbnail async load

kolibri_explore_plugin/assets/src/views/SearchPage.vue, packages/eos-components/src/components/SearchBar.vue
This patch adds the placeholder cards instead of the loading spinner in
the discovery search page.
It also includes some css changes to the searchbar:
* Clean button restyled, bigger and with a circle
* Larger text for the input
https://phabricator.endlessm.com/T32246
=> Discovery: Add loading state to search

kolibri_explore_plugin/assets/src/views/SearchPage.vue, packages/eos-components/src/components/ButtonsBar.vue
* The buttons bar will be shown in the "empty" state and in the "no
results" state, but in the second case without the label.
* The no results message and suggested channels are only shown when a
search is done and there's no results.
https://phabricator.endlessm.com/T32247
=> Discovery: No results state in search

packages/template-ui/src/components/ChannelHeader.vue
The title for small screens is a different element.
https://phabricator.endlessm.com/T32264
=> template: Fix missing class for hasDarkHeader

packages/template-ui/src/components/Breadcrumb.vue
Because these texts can ellipsize.
https://phabricator.endlessm.com/T32233
=> template: Add tooltips to breadcrumbs

packages/eos-components/src/components/Header.vue, packages/template-ui/src/components/ChannelNavBar.vue
This patch removes the negative margin for the Endless logo in the
header, so now the logo will be inside the container, like any other
component.
The negative margin is something that doesn't work correctly with
different screen sizes because the margin is not fixed and can be
smaller than the logo size.
With this change we loose the effect of the logo at the left of the
content with the scroll, but if makes it work correctly with diffrent
sizes.
This patch also hides the endless logo for "xs" sizes, showing it only
if there's no breadcrumb.
https://phabricator.endlessm.com/T32279
=> components: Move logo inside the margins for header

packages/template-ui/src/components/ChannelHeader.vue, packages/template-ui/src/components/ChannelNavBar.vue, packages/template-ui/src/components/mixins/headerMixin.js
And add a button to enlarge the header and show all the description
when it ellipsizes. Per design, we cut at 5 lines.
Also: when a channel has an image asset in the header, use the primary
color instead of the secondary color as fallback. This makes the
background look better in case Endless curated channels do ellipsize
their description (very unlikely). Add a hasHeaderImage computed
property to the mixin for this.
https://phabricator.endlessm.com/T32294
=> template: Ellipsize the header description

packages/template-ui/src/store/index.js
The array of ancestors should be of node objects, not node IDs.
https://phabricator.endlessm.com/T32310
=> template: Fix detail page for flat channels

kolibri_explore_plugin/assets/src/apiResources.js, kolibri_explore_plugin/assets/src/customApps.js, kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue, packages/kolibri-api/index.js, packages/template-ui/channel-overrides/career-girls/options.json, packages/template-ui/src/App.vue, packages/template-ui/src/store/index.js, packages/template-ui/src/views/Section.vue
The career-girls channel has a lot of content and the backend fails when we try to fetch all nodes with:
```
django.db.utils.OperationalError: Expression tree is too large (maximum depth 1000)
```
For channels like that, instead of querying all the content in one request it's possible to get the same data with one request per topic.
=> T32306 async load

kolibri_explore_plugin/assets/src/constants.js, kolibri_explore_plugin/assets/src/views/ChannelsPage.vue, kolibri_explore_plugin/assets/src/views/SearchPage.vue
To get better results from the backend, in particular for the main
buttons.
Also, update the list of search terms.
It's using a Map to ensure order.
https://phabricator.endlessm.com/T32320
=> discovery page: Add synonyms to search terms

packages/eos-components/src/components/TopicCard.vue
In T32077 we made the false assumption that 4 lines of description
would fit when the title is not clamped, and 3 otherwise. But the
title can have 2 lines and still not clamp.
So we have no option but using 3 max lines always for the description.
https://phabricator.endlessm.com/T32326
=> components: Use always 3 max lines for topic description

kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
This is because we have to override all the font rules from the
Kolibri standard theme, which adds Noto to many elements.
https://phabricator.endlessm.com/T32302
=> discovery page: Use Poppins font for buttons

kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
It seems this was copy/pasted from the template carousel, which has an
override option to have/not have the carousel.
https://phabricator.endlessm.com/T32371
=> discovery page: Fix console error for inexistent variable

packages/eos-components/src/components/CardBody.vue
These were never intended to be displayed at the same time.
https://phabricator.endlessm.com/T32360
=> components: Cards: Don't show tags when showing channel info

packages/eos-components/src/components/TopicCard.vue
When the card has channel information (which happens in the landing
page), show it in place of the N resources line.
https://phabricator.endlessm.com/T32356
=> components: TopicCard: show channel

packages/eos-components/src/components/CarouselCard.vue, packages/eos-components/src/components/PlayButton.vue
This patch set the style property nowrap to ensure that we always have
the icon and the text aligned in the PlayButton component.
It also adds some style classes to improve the responsiveness for the
CarouselCard, hidding the subtitle when there's no space.
https://phabricator.endlessm.com/T32389
=> Components: Style Carousel card to avoid button wrap

kolibri_explore_plugin/assets/src/views/AboutModal.vue
- Use h5 for "Release" heading.
- Remove round corners from list group items.
https://phabricator.endlessm.com/T32412
=> discovery page: Improve style in About modal

packages/eos-components/src/components/ChannelCard.vue, packages/template-ui/src/components/ChannelFooter.vue
In this case doing composition is a bit forced because it's not
actually a card, so it doesn't need ellipsizing at max lines. Also,
using composition we had to add too much CSS, it was more complicated.
Also, remove the infoCard variant of ChannelCard.
https://phabricator.endlessm.com/T32388
=> template: Don't overuse the channel card in the footer

kolibri_explore_plugin/assets/src/customApps.js, packages/template-ui/channel-overrides/49ers-edu-digital-playbook/options.json, packages/template-ui/channel-overrides/techbridge-girls-home/styles.scss
- make it a flat grid
- no carousel or filters needed as we only have 8 vidoes and the
full playbook
Change also the order of the tiles so that SF49ers and
Techbridge girls are in row one and two.
https://phabricator.endlessm.com/T32499
=> Channel overrides: adjust representation of the SF49ers channel

packages/template-ui/src/components/FilterContent.vue, packages/template-ui/src/components/FilterResult.vue
ActivityTypes parameter has been renamed to Kinds in the kolibri API,
this patch update this on the plugin.
https://phabricator.endlessm.com/T32573
=> filter: Update filter parameter name

packages/template-ui/src/views/BundleSection.vue
This patch adds the sectionNodes to the getCardSubtitle function call to
be able to calculate correctly the number of resources in this section.
This new bundle object emulates the old node object with the hierarchy
tree, so the function calculate the number of resources correctly.
https://phabricator.endlessm.com/T32758
=> template: Show number of resources in bundle section

kolibri_explore_plugin/assets/src/views/ContentModal.vue
The content modal doesn't use the full screen width so the styles to
show the tips in a second column is not working correctly even in large
screens.
This patch makes the assesment content to show as 100% width and with
smaller bottom padding.
https://phabricator.endlessm.com/T32786
=> discovery: Make AssessmentWrapper to use 100% width

packages/template-ui/src/components/ChannelHeader.vue, packages/template-ui/src/components/mixins/headerMixin.js
- Click does the same as going 1 back in window history.
- Style header buttons. This applies to the more/less buttons too.
- Remove conditional for header image in buttons or header background.
https://phabricator.endlessm.com/T32923
=> template: Add button to go back in Header

kolibri_explore_plugin/assets/src/modules/topicsTree/index.js, kolibri_explore_plugin/assets/src/routes/index.js, kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue
Go back to the corresponding page, not always to the home page as
before.
- vue-router handler: Store the current page in the vuex state before
navigating to the custom presentation.
- Custom channel presentation: Use that state when the event from the
custom presentation happens to navigate programatically to it.
Also fixes the Navigation cancelled error that happened always when
going back from a custom presentation.
https://phabricator.endlessm.com/T32915
=> discovery: Improve going back the custom presentation

packages/template-ui/channel-overrides/wikipedia/components/Breadcrumb.vue
Custom Breadcrumb component for wikipedia override with just the channel
link and no link to content.
https://phabricator.endlessm.com/T32948
=> template: Custom breadcrumb component for wikipedia

kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue, kolibri_explore_plugin/assets/src/views/ExploreIndex.vue, kolibri_explore_plugin/assets/src/views/SearchPage.vue, packages/eos-components/src/components/CollapsibleCardGrid.vue
Use the keep-alive wrap in the SearchPage to keep the page state.
https://phabricator.endlessm.com/T32940
=> discovery: keep the SearchPage state during navigation

packages/eos-components/src/components/mixins/responsiveMixin.js
The kolibri-explore-plugin module is built using kolibri-tools and the
import of styles.scss variables doesn't work there, so the
responsiveMixin is not giving the correct values.
This patch detects the breakpoint in the document styles in real time
instead loading from the scss in build time.
https://phabricator.endlessm.com/T32947
=> components: Detect bootstrap breakpoints in realtime

kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue, kolibri_explore_plugin/assets/src/routes/index.js, kolibri_explore_plugin/assets/src/views/SearchPage.vue
The query attribute was not reset when showing the SearchPage, this
patch sync the query attribute in  the SearchPage with the searchTerm in
the store, and it's set to empty on clicking in the tab.
The searchTerm is not updated with the URL if the query parameter is not
passed as part of the url, so it's keeped when navigating to content and
back.
https://phabricator.endlessm.com/T32988
=> Discovery: Reset search input on Search tab select

kolibri_explore_plugin/assets/src/views/SearchPage.vue, packages/eos-components/src/components/SearchBar.vue
This patch disables the SearchBar input during the loading to avoid
edit the query during a search so the text input is disabled until the
API query is completely done.
After the search the input grab the focus again, so it's easy to change
the query without clicking anywhere.
https://phabricator.endlessm.com/T32917
=> Discovery: Disable search input during search

packages/template-ui/src/App.vue
In App we do a bit of routing when receiving parameters, to go to
either a specific content, topic, or the test page.
We shouldn't account this as two navigations in the browser
history. Use router replace instead of router push to do it.
https://phabricator.endlessm.com/T33012
=> template: Replace route when receiving params

kolibri_explore_plugin/assets/src/customApps.js, packages/template-ui/channel-overrides/wikihow/components/Breadcrumb.vue, packages/template-ui/channel-overrides/wikihow/components/DetailView.vue, packages/template-ui/channel-overrides/wikihow/options.json, packages/template-ui/channel-overrides/wikihow/styles.scss
The custom presentation for wikihow is similar to what we've right now
for wikipedia, just an override of the Breadcrumb and the DetailView to
show the defaultContentNode fullscreen.
https://phabricator.endlessm.com/T33008
=> template: Create channel override for wikihow

packages/template-ui/src/router/index.js, packages/template-ui/src/views/Home.vue
Instead doing the redirection in the component, this patch does the
redirection using a vue-router NavigationGuard so this is done before
loading the Home component.
With this change the ability of loading the first ContentNode setting
the defaultContentNode to true is lost, but it's not a big issue for the
Endless Key.
https://phabricator.endlessm.com/T33009
=> template: Move defaultContentNode logic to a NavigationGuard

packages/template-ui/channel-overrides/wikihow-arts-and-entertainment/options.json, packages/template-ui/channel-overrides/wikihow-computers-and-electronics/options.json, packages/template-ui/channel-overrides/wikihow-hobbies-and-crafts/options.json
This change changes each WikiHow category channel to show the
corresponding default node. It fixes an error in #343 where the default
content node was set to the same value as the full WikiHow channel.
https://phabricator.endlessm.com/T33008
=> Set defaultContentNode for each WikiHow channel

packages/template-ui/src/App.vue, packages/template-ui/src/router/index.js, packages/template-ui/src/store/index.js, packages/template-ui/src/views/Search.vue
Keep alive the Search component to do not loose the search after
clicking on a card and going back.
This patch also introduces a new navigation guard to the Search route so
the search is clean when the from route is the Home. That way the search
is clean when the user clicks in the Search Keywords link.
https://phabricator.endlessm.com/T33025
=> template: Keep the search state

.gitignore, README.md, scripts/_common.py, scripts/ingest_highlighted.py
Add a script that:
- Reads a spreadsheet sheet
- Parses the rows, and
- writes a JSON file.
The sheet has sets of rows. The first set is content to be highlighted
in the Discovery page. The other sets must start with a channel ID,
and it's one set per channel.
The data in the JSON will be used later for filling the carousels with
content with a rotation logic.
Invalid IDs are ignored, except for the channel IDs. If a channel ID
is invalid, we raise an exception to stop execution.
Read spreadsheet key from a local, uncommited `.env` file. Pipenv
handles this automatically. Explain in the README. And add the file to
the list ignored by GIT.
https://phabricator.endlessm.com/T33016
=> scripts: Add script to ingest highlighted content

kolibri_explore_plugin/assets/src/routes/index.js
This patch sets the backFromCustomPage state in every channel route, not
just in the content one, so if after search you click on a topic folder
or a channel card, the close button implements the correct navigation
flow.
https://phabricator.endlessm.com/T33010
=> discovery: Set backFromCustomPage for all channel routes

packages/template-ui/channel-overrides/wikipedia/options.json
This was incorrectly set to the node ID for "100 Wikipedia Articles".
Instead, we should use the "Selected Wikipedia Articles" node.
https://phabricator.endlessm.com/T33053
=> Update defaultContentNode for Wikipedia

kolibri_explore_plugin/assets/src/components/CategorizedChannelsList.vue, packages/eos-components/src/components/SlidableGrid.vue
Make the number of cards inside the slidable grid configurable. And
match the number of columns in the ChannelCardGroup:
- use 3 cards per slide for normal/large screens
- 2 for medium/small screens
- 1 for very small screens
https://phabricator.endlessm.com/T33092
=> discovery: Use 3 cards per slide in categorized channels

kolibri_explore_plugin/assets/src/views/SearchPage.vue, packages/eos-components/src/components/SearchBar.vue, packages/eos-components/src/constants.js, packages/template-ui/src/views/Search.vue
Increase the debounce time to 2 seconds and capture the Enter key event
to trigger the search when it happens.
https://phabricator.endlessm.com/T33126
=> Increase search debounce time and trigger with Enter

packages/template-ui/src/components/FilterResult.vue
This patch makes a copy of the common keywords filter query when
modifying to avoid to modify the object in place. The new array is used
for the query to the API but the state shouldn't be modified.
https://phabricator.endlessm.com/T33128
=> template: Do not modify filter state object inplace

packages/template-ui/src/components/ContentImage.vue
This patch unbind the onload function when loading a new image to avoid
race conditions when the thumbnail changes.
https://phabricator.endlessm.com/T32942
=> template: avoid onload race condition

.github/workflows/lint.yml, .github/workflows/node.yml, .github/workflows/release-apps.yml, scripts/bootstrap.sh
This fixes the issue with the last release of @vue/cli
error open@8.4.0: The engine "node" is incompatible with this module.
Expected version ">=12". Got "10.24.1"
https://phabricator.endlessm.com/T33182
=> CI: Set @vue/cli version to v4.5.15

kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue
This is not needed when clicking on the Channels tab because that view
always refreshes it's content.
Also, fix the Javascript in the method which had commas instead of
semicolons.
https://phabricator.endlessm.com/T33179
=> Discovery: Scroll to top when clicking the Search tab

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js, kolibri_explore_plugin/assets/src/modules/topicsRoot/index.js, kolibri_explore_plugin/assets/src/views/SearchPage.vue
By keeping track of the last promise per each kind, we are able to
ignore the previous ones by not resolving them.
This fixes issues with old promises provoking inconsistent or
duplicate results coming from a previous search.
This is done in a new `searchLastChannels()` method which wraps
`searchChannels()` so it can be easily replaced.
Also, clear the progress bar and mark all promises as "old" when the
component is deactivated.
https://phabricator.endlessm.com/T33202
=> discovery: Ignore previous search promises

kolibri_explore_plugin/assets/src/views/ContentItem.vue
This patch fix the variable name in the ContentItem to load correctly
the extraFields of a content node.
https://phabricator.endlessm.com/T33233
=> discovery: Fix extraFields in ContentItem

kolibri_explore_plugin/assets/src/components/InstallContentModal.vue, kolibri_explore_plugin/assets/src/views/ExploreIndex.vue, kolibri_explore_plugin/views.py
This patch adds the process ID to the tasks created to import the
channels and requeue this tasks if the process ID is different from the
previous one.
This way the stalled jobs will start again if the application is closed
during a content installation.
The task type is also changed to "REMOTEIMPORT", to show these tasks in
the Kolibri device plugin.
https://phabricator.endlessm.com/T33482
=> InstallContent: Requeue stalled jobs

package.json
The map files add some megabytes that aren't needed in production.
https://phabricator.endlessm.com/T33515
=> Remove map files from deployed loadingScreen

kolibri_explore_plugin/views.py, packages/eos-components/src/components/CollectionSelectionModal.vue
The download size unit should be xx bytes. The bytes can be simplified
as capitalized 'B'. The lowercase 'b' represents bit.
https://phabricator.endlessm.com/T33685
=> Fix the size units

kolibri_explore_plugin/assets/src/views/ExploreIndex.vue, kolibri_explore_plugin/options.py, kolibri_explore_plugin/views.py, packages/eos-components/src/components/CollectionSelectionModal.vue, packages/eos-components/src/components/GradeSelectionModal.vue, packages/eos-components/src/components/InstallContentModal.vue
https://phabricator.endlessm.com/T33570
=> Use manifest.json files to download collections

kolibri_explore_plugin/views.py
This patch uses the more simple function _read_pid_file instead of the
get_status to get the process PID so it does less operations and is
faster.
https://phabricator.endlessm.com/T33633
=> Use _read_pid_file instead of get_status

packages/loading-screen/src/App.vue, packages/loading-screen/src/main.js, packages/loading-screen/src/store.js, packages/loading-screen/src/views/UsbDriveConnection.vue
By implementing a simple store without vuex. This removes the
need to override setters in the components. Now the host app
(Android/Windows) can still call APIs like:
`window.setHasUSB(true)` and this is reactive to all the
welcome screen, not just a single component.
=> Welcome screen: Better state management

.github/workflows/release-apps.yml, .gitignore, packages/loading-screen/package.json, scripts/bundle_bundles.py
Pulling the loading-screen JS package out of the python package is cumbersome, so also release it as a ZIP file.
=> Release loading-screen ZIP file

kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue
This was a leftover line inside the map function. The loadingNodes variable should be set to false after all the collections are fetched. As it's already happening in the then() clause.
https://phabricator.endlessm.com/T34521
=> Content packs view: Fix setting loadingNodes

kolibri_explore_plugin/assets/src/modules/coreExplore/utils.js
And return false if any error happens accessing the browser APIs. This would prevent the download for failing in older browsers.
https://phabricator.endlessm.com/T34668
=> User region detection: Wrap in try/catch

packages/eos-components/src/index.scss, packages/eos-components/src/styles.scss
By default the bootstrap theme has 7,5% darken of the normal color. That doesn't work for our current primary color because it's black. So change it to 7.5% lighten.
https://phabricator.endlessm.com/T34616
=> Theme: Use light variant on buttons hover

kolibri_explore_plugin/assets/package.json, kolibri_explore_plugin/assets/src/composables/useContentNodeProgress.js, kolibri_explore_plugin/assets/src/composables/useProgressTracking.js, kolibri_explore_plugin/assets/src/modules/topicsTree/handlers.js, kolibri_explore_plugin/assets/src/views/ContentItem.vue, kolibri_explore_plugin/assets/src/views/ContentModal.vue, kolibri_explore_plugin/collectionviews.py, kolibri_explore_plugin/tasks.py, package.json, yarn.lock
https://phabricator.endlessm.com/T34559
=> T34559 migrate to 16 alpha

kolibri_explore_plugin/assets/src/components/AboutModal.vue
Allow the modal main div to receive keyboard input. Add a listener to the keyup event. Add to check when the user completed the cheat code and to reset the state when a different character is pressed. Load the Device tab in same window when the user completes the cheat code.
https://phabricator.endlessm.com/T34797
=> About modal: Add cheat code to Device tab

kolibri_explore_plugin/assets/src/views/ContentPage.vue
The commit 3c84d23a9e02 ("ContentItem: Adapt to upstream changes") did the corresponding modification for migration kolibri to 16 alpha. Following that, the ContentItem's "content" should be replaced by "ContentNode".
https://phabricator.endlessm.com/T34817
=> ContentPage: Fix ContentPage's contentNode

.github/ISSUE_TEMPLATE/channel-custom-presentation-request.md
This adds an issue template for custom channel presentation requests.
Related: https://github.com/endlessm/endless-key-content-private/issues/45#issuecomment-1567170878
=> Add template for channel override requests

kolibri_explore_plugin/assets/src/components/AboutFooter.vue, kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue, kolibri_explore_plugin/assets/src/views/DiscoveryPageEkIguana.vue, kolibri_explore_plugin/assets/src/views/SearchPage.vue
When these links were moved from the navigation bar to the footer of the landing page, we forgot to also add them to the search page and landing page used by the physical USB. This commit adds them there.
https://phabricator.endlessm.com/T34665
=> Add 'About' footer to search page and Iguana landing page

packages/ek-components/src/components/EkCardBody.vue
Remove unused/unknown elements. Simplify to use divs and remove any flex CSS that is not actually needed.
Issue #534
=> Fix and simplify EkCardBody

.github/release.yml, .github/workflows/main.yml
Make softprops/action-gh-release action generates the release note along with releasing. The release note follows the format of the ducoment "Automatically generated release notes" [1]
[1]: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
Fixes: https://github.com/endlessm/kolibri-explore-plugin/issues/577
=> CI: Generate release note automatically

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js, kolibri_explore_plugin/assets/src/views/SearchPage.vue
This adds a switch to the search results page that controls whether the
results should include content that is not available on the device
(i.e., needs to be downloaded).
Fixes: https://github.com/endlessm/kolibri-explore-plugin/issues/572
=> Search page: Add switch to control showing unavailable content

kolibri_explore_plugin/assets/src/kolibriApi.js, packages/template-ui/src/components/SectionsSearchRow.vue
The button is a stub, it merely redirects to the devices tab, and just redirects to the Devices tab, but I think it at least is visible / hidden correctly.
https://github.com/endlessm/kolibri-explore-plugin/issues/532
=> Add Download button to channels

.github/workflows/bump2release.yml
The build_for_tag job of bump2release.yml will not execute until bump_version job sets the output tagname properly.
This fixes commit 1b8c05e6a04f ("CI: Call the main workflow after bump the version for release").
https://phabricator.endlessm.com/T34804
=> CI: Fix the missed step id for job's output

.github/workflows/bump2release.yml
Build_for_tag's following jobs build_apps-bundle and build_kolibri-explore-plugin_whl will not do the release until main.yml's input tagname is set properly.
This fixes commit 1b8c05e6a04f ("CI: Call the main workflow after bump the version for release").
https://phabricator.endlessm.com/T34804
=> CI: Fix bump_version typo

setup.py
Use pypa/gh-action-pypi-publish [1] action to publish kolibri-explore-plugin wheel. However, the workflow shows error:
Checking dist/kolibri_explore_plugin-6.4.0-py2.py3-none-any.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be
rendered on PyPI.
No content rendered from RST source.
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.
Follow section "Including your README in your package’s metadata" of the document "Making a PyPI-friendly README" [2] to add "long_description" into setup.py.
[1]: https://github.com/pypa/gh-action-pypi-publish
[2]: https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme
Fixes: https://github.com/endlessm/kolibri-explore-plugin/issues/587
=> setup.py: Use README as the long description for PyPI

kolibri_explore_plugin/collectionviews.py
After the `APPLYING_EXTERNAL_TAGS` stage, the DownloadManager will enter a new `IMPORTING_EXTRA_CHANNELS` stage. In this stage, it should download metadata for any channels which are listed in another content collection.
Issue #548
-----
The parent issue here wants this stage to happen in the background, and I took a look at that in #579. But I think there's some overlap with #568, so I'm opting for something quick and dirty in this pull request and we can deal with downloading channel metadata in the background _separately_.
=> Download: Add a stage to import all channels

.github/workflows/bump2release.yml, .github/workflows/lint.yml, .github/workflows/main.yml, .github/workflows/node.yml
The action/checkout@v3's ref [1] is the reference or SHA when trigger the workflow by default. So, the checkout action will not checkout at the tag until the "ref" is specified with a tag name.
This commit lists the scenarios of both workflow_call and non-workflow_call for action/checkout and softprops/action-gh-release.
[1]: https://github.com/actions/checkout/blob/v3.5.3/README.md#usage
Fixes: https://github.com/endlessm/kolibri-explore-plugin/issues/589
=> CI: Fix checkout branch for bump version from wrokflow

packages/template-ui/src/main.js
The next commit will add the first translatable EK component. But the i18n from Kolibri isn't hooked with the template-ui. So add a dummy function that will return the English string to avoid the template from failing and to keep Discovery/Library using translations.
Issue: #568
=> Template: Workaround i18n

kolibri_explore_plugin/assets/src/kolibriApi.js, packages/template-ui/src/views/Search.vue
There are two open questions about this PR:
* How to handle translatable strings?
* ~~The initial state of the check button must come from `plugin_data` somehow. How?~~
* I've worked around this by adding a global getter to the KolibriApi class. It seems to work in practice, but please let me know if the approach is wrong.
Other than that, seems to work.
https://github.com/endlessm/kolibri-explore-plugin/issues/569
=> Filter unavailable content in Channel view

kolibri_explore_plugin/assets/src/kolibriApi.js, kolibri_explore_plugin/assets/src/modules/coreExplore/actions.js, kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js, kolibri_explore_plugin/assets/src/views/SearchPage.vue, kolibri_explore_plugin/kolibri_plugin.py, kolibri_explore_plugin/options.py
This commit drops the NAVIGATE_UNAVAILABLE option from kolibri-explore-plugin, and hardcodes the behavior to the same as if the option had been set to true.
This does not bring any functional change in comparison to running the plugin with KOLIBRI_NAVIGATE_UNAVAILABLE=1.
https://github.com/endlessm/kolibri-explore-plugin/issues/599
=> Drop NAVIGATE_UNAVAILABLE plugin option

kolibri_explore_plugin/assets/src/kolibriApi.js, kolibri_explore_plugin/assets/src/modules/coreExplore/actions.js, kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js, kolibri_explore_plugin/assets/src/views/SearchPage.vue, packages/template-ui/src/views/Search.vue
Invert the logic so when the UI component is active the content that is
not downloaded on the device is hidden.
https://github.com/endlessm/kolibri-explore-plugin/issues/596
=> Invert show/hide available content logic

README.md
Split the releasing into sections:
* Release with local environment
* Release with GitHub action
This helps providing more detail informaiton of releasing with "Bump version to release" action on GitHub.
Fixes: https://github.com/endlessm/kolibri-explore-plugin/issues/594
=> README: Update releasing with GitHub action

kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue, kolibri_explore_plugin/kolibri_plugin.py, kolibri_explore_plugin/options.py
This will allow the feedback form to differ between the offline and online Kolibri instances.
Fixes: https://github.com/endlessm/endless-key-content-private/issues/62
=> options: Allow feedback URL to be configured

packages/template-ui/src/components/SectionsSearchRow.vue
It was agreed on, as it doesn't do what people
expect it to do.
=> SectionsSearchRow: Hide download button

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
This forces a reload of the main page when the app starts, to work around a problem where the cards never finish loading on that page.
https://github.com/endlessm/kolibri-explore-plugin/issues/598
=> handlers: Work around cards not being loaded when app starts

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
These hardcoded nodes are for EK Iguana (USB) which has a fixed presentation. But the dynamic collections don't have them, so they are provoking 404s and doing unneeded calculations on startup.
#598
=> Startup: Don't fetch carousel for collections

.flake8, .gitignore, .pre-commit-config.yaml, Pipfile, Pipfile.lock, kolibri_explore_plugin/collectionviews.py, kolibri_explore_plugin/tasks.py, kolibri_explore_plugin/vendor/file_transfer.py, pyproject.toml
Since 0.16.0-alpha13, Kolibri's `FileDownload` class uses HTTP range requests to move towards resumable downloads. This significantly slows down network throughput for large downloads as it requires many serial requests to retrieve a single file. Upstream has been made aware and will presumably fix the regression.
In the meantime, this vendors the `FileDownload` code from 0.16.0-alpha12 and adds the necessary plumbing to use it. Comparing the `FileDownload` implementation with the inventor pack, I measured the following timings for the initial content pack download:
Upstream FileDownload:
Start 14:15:18,457
End 14:22:32,008
Total 7m14s
0.16.0-alpha12 FileDownload:
Start 14:09:19,618
End 14:12:01,681
Total 2m42s
#627
=> Vendor old file download code

kolibri_explore_plugin/__init__.py, kolibri_explore_plugin/apps_config.py, kolibri_explore_plugin/collectionviews.py, kolibri_explore_plugin/tasks.py
In order to provide a rich display of unavailable content, thumbnails for the missing content is desired. When downloading the starter pack content, request all thumbnails for each channel. This is a new option for the `remotecontentimport` Kolibri task added after 0.16.0-alpha14. The option is ignored on older releases.
#549
=> Download backend: Request all thumbnails for channel

kolibri_explore_plugin/collectionviews.py
In a previous change, the `_get_channel_metadata` function was moved outside `EndlessKeyContentManifest`. However, this was not corrected in `get_contentthumbnail_tasks`.
https://github.com/endlessm/kolibri-explore-plugin/issues/648
=> Download: Fix error downloading thumbnails

.github/workflows/main.yml
Add trigger_endless-key-app job to trigger Endless Key app build with the new kolibri-explore-plugin release with the webhook.
https://phabricator.endlessm.com/T34806
=> CI: Trigger Endless Key app build with new kolibri-explore-plugin release

.github/workflows/main.yml
The node script passed to the `github_script` action needs to have the `VERSION` value derived from the `env` context rather than expecting it to be resolved like a shell variable.
https://phabricator.endlessm.com/T34806
=> CI: Fix version substitution in endless-key-app trigger

kolibri_explore_plugin/assets/src/app.js, kolibri_explore_plugin/assets/src/components/AboutFooter.vue, kolibri_explore_plugin/kolibri_plugin.py
These will allow the user to install the Endless Key app, if that would be a better fit for them on their device than using key.endlessos.org in a browser.
The badges came from:
- https://play.google.com/intl/en_us/badges/
- https://apps.microsoft.com/store/app-badge
Getting them the same size was a complete pain because, for no good reason, Google have baked a transparent border into the image they serve to you. We have to use the image they serve because otherwise we’d have to carry 20 different localised versions.
Changing the layout to match the design
(https://github.com/endlessm/endless-key-content-private/issues/64#issuecomment-1592442043) required splitting the footer bar into two separate containers, to allow for grouping the links/buttons at the start and end of the footer row. …
=> footer: Add app install links for Play and Microsoft stores

kolibri_explore_plugin/assets/src/components/AboutFooter.vue
showStoreButtons is meant to be true only if both the
androidApplicationId and windowsApplicationId are defined. However the
test was implemented as comparing them to empty string. When they are
not defined, they take the value `undefined` which is not equal to empty
string. As a result, the Google Play and Microsoft Store buttons are
shown in the Android app (and probably also in the Windows app).
Instead, use double-negation to treat both empty string and undefined as
false, and a non-empty string as true.
> !!undefined
false
> !!''
false
> !!"org.endlessos.Key"
true
=> footer: Correctly hide store buttons in apps

kolibri_explore_plugin/assets/src/components/AboutFooter.vue
When supported, use this API to provide a slightly more streamlined experience for installing the Android app when pressing the “Get it on Google Play” button.
The API is only supported by Chrome, on mobile, if the app is advertised as a related application in the PWA manifest for the site, and if the app is not already installed.
The full list of requirements are here:
https://developer.chrome.com/blog/app-install-banners-native/#what-are-the-criteria
If the API is not supported, the button will function as a link as normal.
https://github.com/endlessm/endless-key-content-private/issues/64
=> footer: Use Native App Install Prompt to install Android app

.github/workflows/main.yml, scripts/trigger_jenkins.py
Add trigger_kolibri-installer-android job to trigger "kolibri-installer-android" job on EOSF's Jenkins with the new kolibri-explore-plugin release. It will execute the new introduced trigger_jenkins.py using python-jenkins API to send a webhook.
https://phabricator.endlessm.com/T34805
=> CI: Trigger kolibri-installer-android job with new kolibri-explore-plugin release

packages/ek-components/src/components/EkCardBody.vue, packages/ek-components/src/components/EkCarouselCardTitle.vue, packages/ek-components/src/components/EkChannelCard.vue, packages/ek-components/src/components/EkTopicCard.vue
For text that may be ellipsized, include a "title" attribute with the full text so it appears as a tooltip in most web browsers.
=> Add title attribute for clamped text

packages/welcome-screen/src/views/PackSelection.vue
PackSelection has an EkSlidableGrid, not an EkChannelCard, so removing the 'hasWhiteBackground' property was a mistake.
Reinstate that.
=> PackSelection: Reinstate white background

packages/ek-components/src/components/EkPlayButton.vue, packages/ek-components/src/constants.js
Adapt to mediatypes missing from Kolibri like 'h5p'.
Resolves #560
=> Add labels for missing media types

kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue
The featured channels in the collection may be unavailable because the collection is not importing any content from them. Still they should appear in the Featured row.
=> Discovery page: Allow unavailable featured channels

packages/template-ui/src/components/MainSections.vue
This is mostly a workaround to how Bootstrap styles pill-like buttons by default. It only applies to the pills at channel views, which are the most visible ones.
https://github.com/endlessm/kolibri-explore-plugin/issues/694
---
| Comparison |
|---|
| Before: |
| ![image](https://github.com/endlessm/kolibri-explore-plugin/assets/3518204/a2ef221c-1a4d-4f54-864d-7df1f86acd4c) |
| After |
| ![image](https://github.com/endlessm/kolibri-explore-plugin/assets/3518204/33aa3a4f-fd3b-45ce-a8ba-68bf45e7ac05) |
=> MainSections: Center pill text

packages/ek-components/src/components/EkPlayButton.vue
My ChromeOS test machine has Android WebView 68, which doesn’t support this operator. That causes a syntax error when loading the kolibri-explore-plugin, and hence the app never loads.
Nowhere else in the code is the nullish coalescing operator used, so let’s get rid of this instance for now.
It’s apparently supported by WebView 80 onwards
(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing#browser_compatibility). I don’t know if we want to depend on that yet.
Helps: #156
=> EkPlayButton: Don’t use nullish coalescing operator

kolibri_explore_plugin/api_urls.py, kolibri_explore_plugin/assets/src/apiResources.js, kolibri_explore_plugin/assets/src/kolibriApi.js, kolibri_explore_plugin/assets/src/modules/coreExplore/actions.js, kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js, kolibri_explore_plugin/assets/src/views/ContentPage.vue, kolibri_explore_plugin/assets/src/views/SearchPage.vue, kolibri_explore_plugin/viewsets.py
Add custom content API endpoints that don't use caching in the browser or server to ensure that fresh content is always returned. The content cache key as `ETag` is preserved so that the server can still return early when the browser includes the current content cache key in an `If-None-Match` header. I'm sure I'm "doing it wrong" in JS.
The last commit fixes a minor issue where upstream's channel import tasks don't update the content cache key if the channel doesn't have any nodes. See https://github.com/learningequality/kolibri/pull/10899.
I'm marking this as a draft since the commits need a bit of polish and probably more testing, but in some light testing it seems to fix the stale cached content data issues we've been hitting.
Fixes: #687
=> Disable content caching

Pipfile.lock, scripts/bootstrap.sh
The [CI](https://github.com/endlessm/kolibri-explore-plugin/actions/runs/5532800096/jobs/10095397076) is failed, because bumpversion finds the modified Pipfile.lock.  The modification comes from bootstrap scripts' [`pipenv install --dev`](https://github.com/endlessm/kolibri-explore-plugin/blob/04b5ceb8721a0eae315d613f589858a20019899f/scripts/bootstrap.sh#L5).
According to [Pipfile & Pipfile.lock](https://pipenv.pypa.io/en/latest/pipfile/), both Pipfile and Pipfile.lock should be in version control to secure dependent packages' version.
=> Pipfile: Update Pipfile.lock for dependent packages management

.github/workflows/bump2release.yml, .github/workflows/main.yml, .github/workflows/node.yml, scripts/bootstrap.sh
Passing `--ci` will cause `--ignore-pipfile` to be passed to `pipenv install`, which will cause it to only use the `Pipfile.lock` for installing dependencies, and not install the latest versions which match `Pipfile`, or to update the `Pipfile.lock`. This means that the dependency versions used in CI are properly pinned, and hence we’re not testing them as well as whatever changes are in the associated PR at the same time.
`bootstrap.sh` unfortunately can’t be used from `node.yml` because it benefits from using `actions/setup-node` to cache the node installation.
Prompted by https://github.com/endlessm/kolibri-explore-plugin/pull/701
=> ci: Add --ci argument to bootstrap.sh and use it from CI jobs

MANIFEST.in
This file is generated at build time and needed by at runtime by Kolibri.
Closes https://github.com/endlessm/kolibri-explore-plugin/issues/703
=> build: Include build/kolibri_explore_plugin.app_stats.json

kolibri_explore_plugin/assets/src/customApps.js, packages/template-ui/channel-overrides/blockly-games/options.json
We have created a new custom channel only containing the Spanish and English Blockly content to allow for easier consumption. The view does not need to be flat anymore in that case.
https://github.com/endlessm/kolibri-explore-plugin/issues/708
=> Blockly override: new layout for custom EN/ES channel

packages/template-ui/channel-overrides/ted-ed-lessons/options.json
We simplified the TED-Ed channel to not have bundles anymore, just the videos. Remove the bundle specific custom presentation.
https://github.com/endlessm/kolibri-explore-plugin/issues/730
=> Channel override: adjust representation for the removal of bundles

babel.config.js, package.json, packages/ek-components/babel.config.js, packages/ek-components/package.json, packages/template-ui/.browserslistrc, packages/template-ui/babel.config.js, packages/template-ui/package.json, packages/welcome-screen/.browserslistrc, packages/welcome-screen/babel.config.js, packages/welcome-screen/package.json, yarn.lock
This was missing, meaning the default babel config was being used when
building the whole of kolibri-explore-plugin.
This meant that transpilation and ES5 polyfills were not being applied.
Signed-off-by: Philip Withnall <philip@tecnocode.co.uk>
Fixes: https://github.com/endlessm/kolibri-installer-android/issues/159
=> build: Add missing babel config for root package

scripts/bootstrap.sh
If you don't specify any options to bootstrap.sh, `pipenv_install_args` will retain its default of an empty string and pipenv will be passed an empty quoted argument. That's wrong and some versions of pipenv fail expecting the argument to be a package requirement.
Instead, initialize the variable as an array and append to it as needed. Bash expands an empty array to nothing using the `"${var[@]}"` notation.
=> Fix bootstrap arguments passed to pipenv

kolibri_explore_plugin/assets/src/modules/manageContent/handlers.js, kolibri_explore_plugin/collectionviews.py, kolibri_explore_plugin/tasks.py
When we enqueue the `remotecontentimport` task from `CollectionDownloadManager`, we can specify the priority of the jobs as high. However, when a user initiates a content download from the frontend using the tasks API, that's not possible. Since the upstream default priority is regular, it can get blocked behind any other queued tasks such as the background thumbnail downloads.
This adds a copy of upstream's `remotecontentimport` with the default priority set to high and arranges for it to be used throughout the plugin.
Helps: #739
=> Override remotecontentimport task priority to high

kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue
The featured channels for the discovery page were being constructed by finding the root node for channels tagged with `featured-channel`. However, using the node list directly breaks the fallback in `getChannelIcon` to use the channel's inlined thumbnail since the root node may not have a thumbnail specified. Instead, use the equivalent node from `rootNodes` since those already have the thumbnails resolved.
Fixes: #642
=> Fix featured channel icons on discovery page

packages/template-ui/src/components/Breadcrumb.vue, packages/template-ui/src/components/ChannelFooter.vue, packages/template-ui/src/components/EmptyResultsMessage.vue, packages/template-ui/src/components/FilterContent.vue, packages/template-ui/src/components/FilterDropDown.vue, packages/template-ui/src/components/MainSections.vue, packages/template-ui/src/components/SectionsSearchRow.vue, packages/template-ui/src/views/BundleSection.vue, packages/template-ui/src/views/Content.vue, packages/template-ui/src/views/Search.vue, packages/template-ui/src/views/Test.vue
Previously they were hard-coded as English. A few strings were translatable, but most weren’t.
Signed-off-by: Philip Withnall <philip@tecnocode.co.uk>
Fixes: #772
=> template-ui: Make various UI strings translatable

kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue
The previous fix to use `rootNodes` didn't work since that's populated asynchronously. Rather than try to block on that, this just repeats the channel lookup and mutates the node to have the channel's thumbnail fallbacks.
Fixes: #780
=> Really fix featured channel icons on discovery page

package.json
This is currently breaking the release because `i18n-extract-backend` always causes the `en.po` file to be updated. This in turn causes `setuptools_scm` to create a dev version of the wheel, which is promptly rejected by PyPI. For now, drop `build:i18n` from the generic `build` script until a better fix can be found.
Fixes: #787
=> Don't run build:i18n from build script

kolibri_explore_plugin/urls.py
Otherwise running `kolibri manage migrate` fails.
=> Import VERSION properly in urls

.github/workflows/main.yml
The welcome-screen.zip file is intended to be included as a release artifact, but it wasn't actually being built. Add the necessary build step and make `action-gh-release` fail when a pattern doesn't match any files. Without this it just prints a warning:
```
🤔 Pattern 'packages/welcome-screen/welcome-screen.zip' does not match any files.
```
=> Build welcome-screen.zip for release

packages/welcome-screen/src/main.js
The localized ek-components are breaking the PackSelection view. Add the same workaround as template-ui. This should be temporary while we move this view to the plugin.
Helps #780
=> Welcome app: Workaround $tr

.github/workflows/bump2release.yml, .github/workflows/lint.yml, .github/workflows/main.yml, .github/workflows/node.yml
Original Pyhon 3.7 has been EOL since 2023-06-27 [1]. So, update Python to 3.9.
[1]: https://devguide.python.org/versions/#supported-versions
Fixes: https://github.com/endlessm/kolibri-explore-plugin/issues/795
=> Bump Python to 3.9

scripts/_common.py, scripts/build_template_overrides.py, scripts/bundle_bundles.py
Having `bundle_zip` default to LZMA compression meant it also applied to `welcome-screen.zip`. That's problematic since `unzip` can't handle that compression scheme. It's also unnecessary as `welcome-screen.zip` is only intended for releases. All of our apps will expand it into some location in their package, so the compression used is irrelevant.
Instead, make the default zlib deflate compression and explicitly request LZMA compression just for the channel templates. Note that the outer `apps-bundle.zip` is actually created with no compression, which is fine since it's entirely for distributing the already compressed channel templates.
See https://github.com/endlessm/endless-key-flatpak/issues/26.
=> Only use LZMA compression for channel template zips

MANIFEST.in, kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue, kolibri_explore_plugin/assets/src/routes/baseRoutes.js, kolibri_explore_plugin/assets/src/views/ExploreSideNavEntry.js, kolibri_explore_plugin/assets/src/views/commonExploreStrings.js, kolibri_explore_plugin/buildConfig.js, kolibri_explore_plugin/kolibri_plugin.py
This makes it possible for a user to navigate back to the Discovery UI from other parts of Kolibri.
Helps: https://github.com/endlessm/endless-key-flatpak/issues/26
-----
In particular, this was helpful with the Endless Key desktop app for a case where the default landing page is Kolibri's Device page.
=> Add Explore to Kolibri's sidebar

package.json
It turns out that kolibri-tools only accepts one
`--namespace`/`--searchPath` argument pair on the command line, and silently ignores all of them except the last one that you provide.
This means the previous command was not extracting translatable messages for ek-components or template-ui, just the main plugin and the welcome-screen (which was the last pair of arguments).
Rearrange the commands so that each plugin/package is extracted separately. This works for message extraction, but unfortunately each invocation of `kolibri-tools` currently deletes *all* CSV files in the target directory, so we’re left with only the final CSV file.
That’s fixed by https://github.com/learningequality/kolibri/pull/11226. In the meantime, whoever periodically regenerates the CSV/JSON files will need to do …
=> build: Rework kolibri-tools commands for extracting translation messages

packages/ek-components/src/components/EkCollapsibleCardGrid.vue, packages/ek-components/src/components/EkSearchBar.vue, packages/ek-components/src/components/EkSlidableGrid.vue, packages/ek-components/src/components/EkTopicCard.vue, packages/template-ui/src/components/Breadcrumb.vue, packages/template-ui/src/components/ChannelFooter.vue, packages/template-ui/src/components/EmptyResultsMessage.vue, packages/template-ui/src/components/FilterContent.vue, packages/template-ui/src/components/FilterDropDown.vue, packages/template-ui/src/components/MainSections.vue, packages/template-ui/src/components/SectionsSearchRow.vue, packages/template-ui/src/views/BundleSection.vue, packages/template-ui/src/views/Content.vue, packages/template-ui/src/views/Search.vue, packages/template-ui/src/views/Test.vue
The standalone packages have temporary `$tr` placeholders that don't currently handle translation objects or placeholders. For `stable`, revert the recent translation changes to essentially go back to the hardcoded English strings. The proper i18n fixes will land on `master` and full localization can be enabled for the the next major version.
See #797 for an example of current broken translations.
=> Remove package localization

kolibri_explore_plugin/migrations/0002_backgroundtask.py, kolibri_explore_plugin/test/test_migrations.py
There were a few problems here:
* `Job`s have no `fun` attribute. It should be `func`.
* Since a forward code migration was provided but no reverse code migration, Django assumes the the migration is not reversible.
* `job_storage` was not being imported from where it's defined. That would make it difficult to mock in tests.
* The JSON encoded parameters weren't sorted, which would make them impossible to test.
A test is added to verify that the `RunPython` migration code actually works.
Fixes: #802
=> Fix BackgroundTask migration

kolibri_explore_plugin/assets/src/views/DownloadPage.vue
Previously, the page was reloaded using a particular effect of the Vue router's go() method, which behaved unexpectedly in some versions of WebKit.
Fixes: https://github.com/endlessm/kolibri-explore-plugin/issues/804
=> DownloadPage: Reload using the location API

kolibri_explore_plugin/assets/src/kolibriApi.js, packages/template-ui/src/main.js
Pass the message ID through the API provided by the plugin.
On the plugin side, use kolibri i18n utility to create a translator for the given namespace and return the translated message.
Helps #604
=> template-ui: Hook i18n

kolibri_explore_plugin/assets/src/views/SearchPage.vue
This was introduced in 075a001cc0898a6567385e1876616741ec3c3746 when `MediaTypeVerbs[]` was replaced by `mediaTypeVerb()`.
=> app: Fix typo in function call in SearchPage

packages/ek-components/src/constants.js, packages/ek-components/src/utils.js
`createTranslator()` in ek-components now relies on `window.kolibri` being available, and that’s only initialised as part of the app setup, which is after all the imports are processed.
This causes the `createTranslator()` calls to fail at import time as `window.kolibri` is undefined.
Fix that by wrapping them in an internal function, which is only called when translated strings are actually needed. Rely on `createTranslator()` to cache the translator between calls.
Fixes: #817
=> ek-components: Delay calling createTranslator() until actually needed

.github/workflows/main.yml
We always build the wheel and tarball for every build. Rather than throwing them away, store them as artifacts. After that, rearrange the release into a separate job that downloads the built artifacts and includes them as release artifacts.
=> Save wheel and tarball as artifacts

.bumpversion.cfg, .pre-commit-config.yaml, README.md, scripts/bump_version.py
This adds some support for creating release candidates with `bumpversion`. Since `pip` considers a package with an `rc<N>` suffix to be a pre-release, it won't be installed without specifying the version or using `--pre`. This should allow us to get some testing on a Narwhal RC without making it generally available.
=> Support release candidates

kolibri_explore_plugin/assets/src/components/AboutModal.vue, kolibri_explore_plugin/assets/src/constants.js, kolibri_explore_plugin/assets/src/views/DevTag.vue, kolibri_explore_plugin/assets/src/views/DiscoveryPageEkIguana.vue, kolibri_explore_plugin/assets/src/views/SearchPage.vue
Signed-off-by: Philip Withnall <philip@tecnocode.co.uk>
Fixes: #773
=> kolibri_explore_plugin: Make various UI strings translatable

kolibri_explore_plugin/assets/src/views/welcome/PackReadyPage.vue, kolibri_explore_plugin/assets/src/views/welcome/PackSelectionPage.vue, kolibri_explore_plugin/assets/src/views/welcome/WelcomePage.vue
These came from the welcome-screen, and can now be translated as part of the main app.
Helps: #770
=> app: Mark some more strings as translatable

kolibri_explore_plugin/assets/src/kolibriApi.js
This fixes issues when KolibriApi class is used without instantiation, for which translators is undefined.
=> Change KolibriApi translators property to global

package.json, packages/loading-screen/.gitignore, packages/loading-screen/README.md, packages/loading-screen/lang/en-US.json, packages/loading-screen/lang/es-419.json, packages/loading-screen/package.json, packages/loading-screen/src/App.vue, packages/loading-screen/src/main.js, packages/loading-screen/src/views/LoadingError.vue, packages/loading-screen/src/views/LoadingInitial.vue, packages/loading-screen/src/views/LoadingRetry.vue, yarn.lock
Previously they were hard-coded as English.
Signed-off-by: Philip Withnall <philip@tecnocode.co.uk>
Fixes: #770
=> welcome-screen: Make various UI strings translatable

packages/ek-components/src/components/EkCardBody.vue, packages/ek-components/src/components/EkClamp.vue
Two quick fixes for `EkCardBody`, springing from https://github.com/endlessm/kolibri-explore-plugin/issues/810.
Here is a screenshot from the Endless Key app before this change:
… and after this change:
=> Ek card webkit layout fixes

kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue, kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js, kolibri_explore_plugin/assets/src/modules/topicsRoot/index.js, kolibri_explore_plugin/assets/src/views/ExploreIndex.vue, kolibri_explore_plugin/kolibri_plugin.py, kolibri_explore_plugin/options.py, packages/ek-components/src/components/EkBackToTop.vue, packages/ek-components/src/components/EkNavBar.vue
This adds Kolibri's `SideNav` component to `ExploreIndex` when the `ENABLE_SIDE_NAV` option is True. When enabled, it can be toggled by clicking the Endless logo while holding the Ctrl key.
Here is an example, running the Endless Key app but after starting kolibri-daemon like this:
```
env KOLIBRI_ENABLE_SIDE_NAV=yes flatpak run --command=/app/libexec/kolibri-app/kolibri-daemon org.endlessos.Key.Devel
```
I think this is useful for testing the Explore plugin while doing other things with Kolibri (such as managing content or device settings), and my hope is it could replace our "showmedevice" cheat code eventually :)
Note that the SideNav in Kolibri 0.16 unfortunately includes other things which are not the sidebar (specifically a bottom bar thing). So I need to hide those via CSS. But …
=> Add side nav

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
The redirect should happen after the loading state is set. Each handler sets loading to true at the very beginning and to false at the very end. But because of the redirect, the TOPICS handler (showChannels) was starting in the middle of the ROOT handler (decideWelcome). Thus the state was mixed up and not to be trusted.
Fixes #799
=> Handlers: Fix root URL redirect

packages/ek-components/package.json, packages/ek-components/src/index.scss, packages/loading-screen/package.json, packages/loading-screen/src/index.scss, yarn.lock
Add a list of all possible weights for each font (Lato, Poppins) and import them.
This should be done with a single import line, but it fails with wrong paths to the font file. So we have to use the SCSS mixin.
Previously only the default font weight (400) was being imported, so text with other weights looked different depending on the web engine used.
Fixes #810
=> Style: Import all font weights

kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue, kolibri_explore_plugin/kolibri_plugin.py, kolibri_explore_plugin/options.py
As the original feedback URL, it can be overriden with a setting. Useful for changing the ES feeback URL in the online instance.
Unfortunately the plugin option can't be generalized to other languages because the INI file should be kept simple (ie no mapping data type).
Fixes #858
=> Feedback form: Use different URL for Spanish

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
Like in 4deba013. In this case the Topics (home) page could be mounted early when redirected from the Download page. Because the redirect was happening after setting "loading" and "error" to false.
Fixes #799
=> Routing: Fix one more page mounting early

kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue, packages/ek-components/src/components/EkTopicCard.vue, packages/ek-components/src/styles.scss
To make topic cards dark blue.
Use a blue as secondary color and use it in topic cards (previously primary black). Keep the previous secondary color as a custom named color "endless-orange". Use the endless orange in the bottom border of tabs in navbar (discover/library).
Helps #725
=> Theme: Change secondary color

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
Change the assumption for showing the welcome screens: before, when there was content in the database it was assumed to be already downloaded and the download was skipped. Now rely on the presence of a DOWNLOAD_COMPLETED state persisted.
Fix #863
=> Download content pack even when there is content

kolibri_explore_plugin/collectionviews.py
=> 863 followup

Pipfile, Pipfile.lock, kolibri_explore_plugin/views.py
The Kolibri `metadata_cache` decorator is tied to the content lifetime,
but that has nothing to do with the channel app data. Furthermore,
`metadata_cache` in Kolibri 0.16.0-beta6 is broken for this usage since
regular `View` classes don't have `render` functions.
Instead, simply use the `cache_control` decorator to set `max-age=600`.
This caches the responses for 10 minutes. Even though these are likely
very static, I don't want to set these longer for now since we have no
control over when the apps bundle gets updated.
Fixes: https://github.com/endlessm/kolibri-explore-plugin/issues/872
=> Fix channel view with Kolibri 0.16.0-beta6

kolibri_explore_plugin/assets/src/views/DownloadPage.vue
This has regressed in the theme changes.
Helps #725
=> Download page: Make progress bar orange again

docs/i18n.md
Update the documentation with the latest knowledge and workflow based on how we actually ended up doing the Spanish translation.
=> docs: Various updates to the i18n documentation based on recent work

.github/workflows/release.yml
Unlike endless-key-app, the kolibri-installer-android `repository_dispatch` workflow expects to receive the released version, not the tag. Set the version from the tag in the validation job and use it in the kolibri-installer-android triggering job.
Fixes: #895
=> ci: Fix version used for triggering kolibri-installer-android

Pipfile, Pipfile.lock, kolibri_explore_plugin/collectionviews.py, kolibri_explore_plugin/jobs.py, kolibri_explore_plugin/test/test_collectionviews.py, kolibri_explore_plugin/test/test_jobs.py
This allows completing the downloader offline when all content is available by skipping unnecessary channel imports. Otherwise, Kolibri will always tries to import channels in case the remote version has been updated. We don't need that since the desired channel version is specified in the starter pack.
This is on top of #897, which allowed me to confirm it would work and catch a couple bugs I would have otherwise missed.
Fixes: #890
=> Skip downloading when all content available

.flake8, kolibri_explore_plugin/collectionviews.py, kolibri_explore_plugin/jobs.py, kolibri_explore_plugin/test/conftest.py, kolibri_explore_plugin/test/test_collectionviews.py, kolibri_explore_plugin/test/test_jobs.py, kolibri_explore_plugin/test/utils.py
Like was done with channel imports, skip content import tasks if all the resources are already available. This is needed when the device is online because Kolibri will probe the channel data from the server regardless of whether content is needed or not. While working on this, I noticed that extra channel thumbnail downloads may be skipped if the channel was already present.
Sorry this is a bit big. I wanted to be sure there really wouldn't be any network requests if they weren't needed. That involved a bit of work with the test studio server so that it could respond to all the requests without having them stubbed out.
Fixes: #890
=> Skip content import

kolibri_explore_plugin/assets/src/customApps.js
The source files for several channel apps were removed in 40b02b32, but these were still referenced in customApps.js.
Custom thumbnails and icons for these channels are still in the repository, so they are not changed here.
https://phabricator.endlessm.com/T35147
=> Remove discontinued channel apps from customApps.js

kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue, kolibri_explore_plugin/assets/src/mixins/isOfflineMixin.js, kolibri_explore_plugin/assets/src/views/welcome/PackReadyPage.vue, kolibri_explore_plugin/collectionviews.py, kolibri_explore_plugin/test/test_collectionviews.py
https://phabricator.endlessm.com/T35137
=> Support "downloading" a content pack without an internet connection

kolibri_explore_plugin/collectionviews.py
It is possible for COLLECTIONS_STATE to be populated with data from a previous version of kolibri-explore-plugin, which results in unhandled errors in new code which expects it to be in a different format.
https://phabricator.endlessm.com/T35159
=> collectionviews: Ignore session state if it uses the wrong format
