kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue

And set the CSS as "scoped" again. This is not needed anymore because
we have our own Base component.
https://phabricator.endlessm.com/T31231

CustomChannelPresentationApp: Remove CSS overrides

---

kolibri_explore_plugin/assets/src/views/ContentPage.vue
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
kolibri_explore_plugin/assets/src/views/PageHeader.vue

https://phabricator.endlessm.com/T31260

T31260 content page

---

kolibri_explore_plugin/assets/src/constants.js

This is the channel we want to target. Plus the test channel breaks the
custom presentation because we are not filtering the custom-channel-ui node
anymore.
https://phabricator.endlessm.com/T31260

Target the public Sikana (English) channel

---

.pre-commit-config.yaml

https://phabricator.endlessm.com/T31260

Pre commit: use Python 3.7

---

MANIFEST.in

https://phabricator.endlessm.com/T31260

Deploy all apps files

---

kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue
kolibri_explore_plugin/urls.py
kolibri_explore_plugin/views.py

https://phabricator.endlessm.com/T31363

Improve custom app zip urls

---

kolibri_explore_plugin/assets/src/app.js

https://phabricator.endlessm.com/T31424

Improve back button in IE11

---

.bumpversion.cfg
Makefile
README.md
requirements.txt

https://phabricator.endlessm.com/T31413

T31413 bump version

---

kolibri_explore_plugin/assets/src/app.js
kolibri_explore_plugin/assets/src/bootswatch.scss
kolibri_explore_plugin/assets/src/styles.scss
kolibri_explore_plugin/assets/src/variables.scss
package.json
yarn.lock

Use Darkly from: https://bootswatch.com/darkly/
https://phabricator.endlessm.com/T31547

Demo: add bootstrap and dark theme

---

kolibri_explore_plugin/assets/src/components/Footer.vue
kolibri_explore_plugin/assets/src/views/ChannelsPage.vue

Add a fake footer component. The text and links are copied directly from
https://www.endlessos.org/
https://phabricator.endlessm.com/T31549

Demo: Add footer component

---

kolibri_explore_plugin/assets/src/components/ContentProvidersRow.vue

https://phabricator.endlessm.com/T31546

Demo: Add radix to parseInt call

---

kolibri_explore_plugin/assets/src/components/ContentProvidersRow.vue
kolibri_explore_plugin/assets/src/components/TagRow.vue
kolibri_explore_plugin/assets/src/styles.scss
kolibri_explore_plugin/assets/src/views/DemoIndex.vue

https://phabricator.endlessm.com/T31545

T31545 tags component

---

kolibri_explore_plugin/assets/src/components/TagRow.vue

Demo: Fix hover in TabRow cards

---

kolibri_explore_plugin/assets/src/views/Base.vue
kolibri_explore_plugin/assets/src/views/ChannelsPage.vue

https://phabricator.endlessm.com/T31559

Demo: Use bootstrap component instead of KIconButton

---

kolibri_explore_plugin/assets/src/components/TagRow.vue
kolibri_explore_plugin/assets/src/views/DemoIndex.vue

https://phabricator.endlessm.com/T31545

T31545 more tagrow

---

kolibri_explore_plugin/assets/src/chromeos-demo.json
kolibri_explore_plugin/assets/src/components/Footer.vue
kolibri_explore_plugin/assets/src/components/TagRow.vue
kolibri_explore_plugin/assets/src/views/Base.vue
kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue

https://phabricator.endlessm.com/T31568

Demo content

---

kolibri_explore_plugin/assets/src/components/ContentProvidersRow.vue

https://phabricator.endlessm.com/T31541

T31541 main channels

---

kolibri_explore_plugin/assets/src/components/Header.vue
kolibri_explore_plugin/assets/src/components/TagRow.vue
kolibri_explore_plugin/assets/src/views/ChannelsPage.vue

https://phabricator.endlessm.com/T31572

Remove search

---

kolibri_explore_plugin/assets/src/components/Carousel.vue

https://phabricator.endlessm.com/T31541

Demo: Hook content to carousel

---

kolibri_explore_plugin/assets/src/modules/topicsTree/handlers.js
kolibri_explore_plugin/assets/src/views/ContentPage.vue

https://phabricator.endlessm.com/T31571

T31571 refine content

---

kolibri_explore_plugin/views.py

https://phabricator.endlessm.com/T31510

Add content type to AppViewDev response

---

kolibri_explore_plugin/assets/src/views/Base.vue

https://phabricator.endlessm.com/T31674

T31674 x button

---

kolibri_explore_plugin/api_urls.py
kolibri_explore_plugin/assets/src/apiResources.js
kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
kolibri_explore_plugin/assets/src/modules/topicsTree/handlers.js
kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue
kolibri_explore_plugin/kolibri_plugin.py
kolibri_explore_plugin/viewsets.py

https://phabricator.endlessm.com/T31705

Add tags to content nodes

---

kolibri_explore_plugin/viewsets.py

It is more performant to use the queryset parameter in the consolidate
method. See https://github.com/learningequality/kolibri/pull/7941
https://phabricator.endlessm.com/T31711

Sync tags with upstream

---

kolibri_explore_plugin/assets/src/customApps.js

https://phabricator.endlessm.com/T31715

Use the real healthy-living channel id

---

kolibri_explore_plugin/assets/src/views/ContentPage.vue

https://phabricator.endlessm.com/T31806

T31806 navigation

---

README.md

https://phabricator.endlessm.com/T31880

Update README with the changes done mocking nodes

---

kolibri_explore_plugin/assets/src/modules/topicsTree/handlers.js
kolibri_explore_plugin/assets/src/modules/topicsTree/index.js
kolibri_explore_plugin/assets/src/views/ContentLightbox.vue
kolibri_explore_plugin/assets/src/views/ContentPage.vue
kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue
kolibri_explore_plugin/assets/src/views/CustomChannelsPage.vue

https://phabricator.endlessm.com/T31806

T31806 lightbox close

---

kolibri_explore_plugin/assets/src/views/ContentLightbox.vue

https://phabricator.endlessm.com/T31881

ContentLightbox: Remove download and share buttons

---

Pipfile.lock
kolibri_explore_plugin/assets/package.json
packages/eos-components/.eslintrc.js
packages/eos-components/babel.config.js
packages/eos-components/package.json
packages/eos-components/src/components/DummyButton.vue
packages/eos-components/src/main.js
packages/template-ui/package.json

https://phabricator.endlessm.com/T31931

T31931 monorepo

---

packages/template-ui/src/components/PaginatedCardGrid.vue

https://phabricator.endlessm.com/T32004

template: Clear pagination when the filter changes

---

packages/eos-components/package.json
packages/eos-components/src/components/CardGridPlaceholder.vue
packages/eos-components/src/components/CarouselPlaceholder.vue
packages/eos-components/src/styles.scss
packages/template-ui/src/dynamicLoadComponents.js
packages/template-ui/src/store/index.js
packages/template-ui/src/views/Home.vue
yarn.lock

This patch adds some placeholder carousel and first row of content while
loading the content so we give some feedback to the user about the
loading state.
https://phabricator.endlessm.com/T31986

Template: Add placeholder while loading channel

---

.pre-commit-config.yaml
Pipfile.lock
kolibri_explore_plugin/assets/src/styles.scss
kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
package.json
packages/eos-components/package.json
packages/eos-components/src/components/ChannelCard.vue
packages/eos-components/src/components/ChannelCardGroup.vue
packages/eos-components/src/styles.scss
packages/kolibri-api/package.json
packages/pbskids-ui/src/components/Card.vue
packages/template-ui/package.json
packages/template-ui/src/styles.scss
yarn.lock

https://phabricator.endlessm.com/T31935

T31935 maintenance

---

packages/eos-components/package.json
packages/eos-components/src/components/ContentLink.vue
packages/eos-components/src/components/TopicCard.vue
packages/template-ui/src/components/Card.vue
packages/template-ui/src/components/CardBody.vue
packages/template-ui/src/components/HighResCard.vue
packages/template-ui/src/components/LowResCard.vue
packages/template-ui/src/components/RegularCard.vue

https://phabricator.endlessm.com/T31895

T31895 typographic

---

packages/eos-components/src/components/TopicCard.vue
packages/template-ui/src/components/CardBody.vue
packages/template-ui/src/views/Search.vue
packages/template-ui/vue.config.js

Fix of various IE11 problems with the template:
* Arrow buttons
* Card body flex-box positioning
* Fix the search input field
https://phabricator.endlessm.com/T31985

T31985 ie11 fixes

---

kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
packages/eos-components/src/assets/EndlessLogo.svg
packages/eos-components/src/components/Header.vue
packages/eos-components/src/main.js

This patch improves a bit the channels page with a header and the footer.
The header has the search button, but that button doesn't do anything yet, the functionality is not implemented here.
https://phabricator.endlessm.com/T32021

Discovery: Add footer to the channels page

---

packages/kolibri-api/.eslintrc.js
packages/kolibri-api/index.js
packages/kolibri-api/package.json

https://phabricator.endlessm.com/T32022

package: Add lint to kolibri-api

---

kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue
packages/eos-components/src/components/Header.vue
packages/eos-components/src/styles.scss
packages/kolibri-api/index.js
packages/template-ui/src/App.vue
packages/template-ui/src/components/ChannelHeader.vue
packages/template-ui/src/components/ChannelNavBar.vue
packages/template-ui/src/components/mixins/headerMixin.js
packages/template-ui/src/views/Content.vue

https://phabricator.endlessm.com/T31933

template: Add navbar to template

---

packages/eos-components/src/components/SearchBar.vue
packages/eos-components/src/main.js
packages/template-ui/src/views/Search.vue

https://phabricator.endlessm.com/T31938

components: Create new SearchBar component

---

kolibri_explore_plugin/assets/src/modules/coreExplore/utils.js
kolibri_explore_plugin/assets/src/views/AssessmentWrapper/ExerciseAttempts/AnswerIcon.vue
kolibri_explore_plugin/assets/src/views/AssessmentWrapper/ExerciseAttempts/index.vue
kolibri_explore_plugin/assets/src/views/AssessmentWrapper/index.vue
kolibri_explore_plugin/assets/src/views/ContentItem.vue

https://phabricator.endlessm.com/T31894

T31894 assessments

---

packages/template-ui/src/constants.js
packages/template-ui/src/store/index.js
packages/template-ui/src/store/modules/filters.js
packages/template-ui/src/views/Search.vue

https://phabricator.endlessm.com/T31949

T31949 search polish

---

packages/eos-components/src/components/SearchBar.vue
packages/eos-components/src/styles.scss
packages/template-ui/src/App.vue
packages/template-ui/src/views/Search.vue

https://phabricator.endlessm.com/T31949

T31949 search bar

---

packages/eos-components/src/styles.scss
packages/template-ui/src/components/Carousel.vue

https://phabricator.endlessm.com/T31950

Template: Add indicators to carousel component

---

packages/template-ui/src/store/modules/filters.js

* Rename filter label to "Learning activity".
* Use verbs like the play buttons, eg "WATCH" instead of "video".
https://phabricator.endlessm.com/T32092

Template: Rename media type filter and options

---

packages/eos-components/src/components/ChannelCard.vue
packages/eos-components/src/components/ChannelLogo.vue
packages/eos-components/src/main.js
packages/template-ui/src/components/ChannelHeader.vue

https://phabricator.endlessm.com/T32072

T32072 channel icons

---

packages/template-ui/src/views/Search.vue

https://phabricator.endlessm.com/T32100

template: Fix lint warning

---

packages/eos-components/src/components/ChannelLogo.vue

https://phabricator.endlessm.com/T32072

components: Fix ChannelLogo radius

---

packages/eos-components/package.json
packages/eos-components/src/styles.scss
packages/template-ui/src/App.vue
yarn.lock

https://phabricator.endlessm.com/T32065

T32065 fonts

---

kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
kolibri_explore_plugin/assets/src/views/SearchPage.vue

https://phabricator.endlessm.com/T32066

T32066 landing loading

---

packages/template-ui/src/components/EmptyResultsMessage.vue
packages/template-ui/src/views/Home.vue
packages/template-ui/src/views/Search.vue
packages/template-ui/src/views/Section.vue

https://phabricator.endlessm.com/T32070

T32070 unify no result

---

packages/template-ui/src/components/FilterResult.vue
packages/template-ui/src/store/modules/filters.js
packages/template-ui/src/views/Home.vue
packages/template-ui/src/views/Section.vue

https://phabricator.endlessm.com/T31988

Template: Do not include topics in filtering result

---

package.json
scripts/check_can_relese.sh

Add a bash script for checking if all is pushed to the remore.
https://phabricator.endlessm.com/T32041

scripts: Check all is pushed before releasing

---

channel-overrides.scss
package.json
packages/eos-components/package.json
packages/eos-components/src/overrides/styles.scss
packages/eos-components/src/styles.scss
packages/eos-components/vue.config.js
packages/template-ui/vue.config.js

https://phabricator.endlessm.com/T32016

T32016 fix build

---

kolibri_explore_plugin/assets/src/views/SearchPage.vue
packages/eos-components/src/components/CardGrid.vue
packages/eos-components/src/components/ChannelCard.vue
packages/eos-components/src/components/ChannelLogo.vue
packages/eos-components/src/components/GridPage.vue
packages/eos-components/src/components/PaginatedCardGrid.vue
packages/eos-components/src/components/PlayButton.vue
packages/eos-components/src/components/RegularCard.vue
packages/eos-components/src/components/SlidableCardGrid.vue
packages/eos-components/src/components/TopicCard.vue
packages/template-ui/src/components/Carousel.vue
packages/template-ui/src/store/index.js

https://phabricator.endlessm.com/T31944

T31944 cards row

---

packages/template-ui/src/store/index.js
packages/template-ui/src/views/Content.vue

https://phabricator.endlessm.com/T32091

T32091 next in topic

---

.gitignore
README.md
kolibri_explore_plugin/assets/src/views/DevTag.vue
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
kolibri_explore_plugin/templates/explore/explore.html
kolibri_explore_plugin/views.py
package.json
scripts/build_info.sh
scripts/clean.sh

https://phabricator.endlessm.com/T32125

Discovery: Add development version info tag

---

packages/eos-components/src/components/ChannelLogo.vue

Remove the special case. Also, move the static style to the `<style>`
part.
https://phabricator.endlessm.com/T32140

components: Channel logo: Remove case for transparent backgrounds

---

packages/eos-components/src/components/Card.vue
packages/eos-components/src/components/CardBody.vue
packages/eos-components/src/components/CarouselCard.vue
packages/eos-components/src/components/mixins/cardMixin.js
packages/eos-components/src/main.js
packages/eos-components/src/utils.js

https://phabricator.endlessm.com/T32136

T32136 carousel

---

kolibri_explore_plugin/assets/src/modules/topicsTree/handlers.js
kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue
packages/eos-components/src/components/mixins/cardMixin.js

https://phabricator.endlessm.com/T32143

T32143 fix console error

---

packages/template-ui/src/App.vue
packages/template-ui/src/components/FilterContent.vue
packages/template-ui/src/components/FilterDropDown.vue
packages/template-ui/src/store/modules/filters.js

https://phabricator.endlessm.com/T32082

T32082 filter dropdown

---

packages/template-ui/channel-overrides/pbs-kids/options.json
packages/template-ui/src/store/index.js
packages/template-ui/src/views/BundleSection.vue
packages/template-ui/src/views/ListSection.vue
packages/template-ui/src/views/Section.vue

https://phabricator.endlessm.com/T31752

T31752 pbs

---

packages/eos-components/src/components/CardBody.vue
packages/eos-components/src/components/PlayButton.vue
packages/eos-components/src/components/RegularCard.vue

Move play button to the bottom. Change tags.
https://phabricator.endlessm.com/T32078

components: Redesign content card

---

packages/eos-components/src/constants.js
packages/template-ui/src/store/modules/filters.js

The options are all different integer numbers. Bad-listing it for now.
https://phabricator.endlessm.com/T32177

template: Remove duration filter

---

packages/eos-components/src/styles.scss

https://phabricator.endlessm.com/T32176

theme: Update media colors

---

packages/eos-components/src/components/Header.vue

For adding the shadow on scroll I first tried using an external
library that adds a v-scroll directive. I couldn't make it work so I
implemented the functionality myself. But I also left the directive
which is raising an error because it doesn't exist.
https://phabricator.endlessm.com/T32175

components: Fix console error in Header

---

packages/eos-components/src/components/Card.vue
packages/eos-components/src/components/TopicCard.vue
packages/eos-components/src/utils.js
packages/template-ui/src/store/index.js
packages/template-ui/src/views/BundleSection.vue

https://phabricator.endlessm.com/T32075

T32075 bundles

---

kolibri_explore_plugin/assets/src/views/ContentModal.vue
packages/eos-components/src/styles.scss

https://phabricator.endlessm.com/T32189

T32189 lightbox scroll

---

packages/template-ui/src/components/Breadcrumb.vue

As per the playthrough today.
https://phabricator.endlessm.com/T32190

template: Make breadcrumb icon clickable

---

kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue

This patch adds an overlay to show a loading screen during the load of
the custom channel presentation iframe.
https://phabricator.endlessm.com/T32182

Discovery: Add loading overlay to custom channel view

---

packages/eos-components/src/styles.scss
packages/template-ui/src/views/BundleSection.vue
packages/template-ui/src/views/Content.vue

https://phabricator.endlessm.com/T32191

Template: Show paragraphs in content description

---

packages/eos-components/src/components/PlayButton.vue
packages/eos-components/src/styles.scss
packages/template-ui/src/components/FilterDropDown.vue
packages/template-ui/src/store/modules/filters.js

https://phabricator.endlessm.com/T32094

template: Use PlayButton for media type filter

---

packages/template-ui/src/components/SectionsSearchRow.vue

https://phabricator.endlessm.com/T32042

template: Improve SectionsSearchRow responsiveness

---

kolibri_explore_plugin/assets/src/constants.js
kolibri_explore_plugin/assets/src/routes/index.js
kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue
kolibri_explore_plugin/assets/src/views/DevTag.vue
packages/template-ui/src/App.vue

https://phabricator.endlessm.com/T32141

Discovery page: Add theme debugging in the development info modal

---

packages/template-ui/src/components/DetailView.vue
packages/template-ui/src/views/BundleSection.vue
packages/template-ui/src/views/Content.vue

https://phabricator.endlessm.com/T32075

Bundles layout from livecoding

---

kolibri_explore_plugin/assets/src/views/ExploreIndex.vue

As per design. Use bounceAlt from loading.io .
https://phabricator.endlessm.com/T32211

Channel loading: Change CSS animation

---

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
packages/eos-components/src/components/CardBody.vue

https://phabricator.endlessm.com/T32067

Discovery: Add channel icon to cards in search

---

packages/eos-components/src/components/PlayButton.vue

Adjust to new spec:
- Use small variant (12 px text).
- Adjust padding using Bootstrap utility classes.
- Fix vertical alignment of the button label.
- Remove border.
https://phabricator.endlessm.com/T32145

components: Improve play buttons style

---

packages/eos-components/src/components/CardBody.vue

By filtering the null values.
https://phabricator.endlessm.com/T32078

components: Fix empty tags in card body

---

kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
packages/eos-components/src/components/ButtonsBar.vue
packages/eos-components/src/components/Header.vue
packages/eos-components/src/main.js

https://phabricator.endlessm.com/T32213

T32213 responsive navigation bar

---

packages/eos-components/src/components/ChannelLogo.vue
packages/eos-components/src/styles.scss
packages/template-ui/src/components/Breadcrumb.vue

https://phabricator.endlessm.com/T32233

T32233 breadcrumbs

---

packages/eos-components/src/components/CardBody.vue
packages/eos-components/src/components/TopicCard.vue
packages/eos-components/src/components/mixins/cardMixin.js
packages/eos-components/src/styles.scss
packages/eos-components/src/utils.js
packages/template-ui/src/App.vue
packages/template-ui/src/views/Test.vue

https://phabricator.endlessm.com/T32077

T32077 cards

---

kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
packages/eos-components/src/components/CarouselCard.vue
packages/eos-components/src/components/CarouselPlaceholder.vue
packages/template-ui/src/views/Content.vue

https://phabricator.endlessm.com/T32235

Livecoding

---

kolibri_explore_plugin/assets/src/views/ContentItem.vue
kolibri_explore_plugin/assets/src/views/ContentModal.vue
packages/eos-components/src/styles.scss

https://phabricator.endlessm.com/T32187

ContentModal: Use a dark styled top bar for content

---

kolibri_explore_plugin/assets/src/views/ContentModal.vue

https://phabricator.endlessm.com/T32130

ContentModal: Add special style rules for zim content

---

kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
kolibri_explore_plugin/assets/src/views/SearchPage.vue

https://phabricator.endlessm.com/T32245

Discovery: Restyle header

---

kolibri_explore_plugin/assets/src/constants.js
kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
kolibri_explore_plugin/assets/src/views/DiscoveryFooter.vue
kolibri_explore_plugin/assets/src/views/SearchPage.vue

https://phabricator.endlessm.com/T32244

T32244 discovery empty state

---

packages/eos-components/src/components/CarouselCard.vue

The Carousel components wraps each CarouselCard with a ContentLink that
should receive the click event so we can't stop the event emission from
the card.
https://phabricator.endlessm.com/T32273

Components: Propagate CarouselCard click event

---

packages/eos-components/src/components/ButtonsBar.vue

https://phabricator.endlessm.com/T32213

discovery page: Add missing margin to buttons dropdown

---

kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
packages/eos-components/src/components/SearchButton.vue
packages/eos-components/src/main.js
packages/template-ui/src/components/SectionsSearchRow.vue

Also, refactor the 2 buttons in a single component.
https://phabricator.endlessm.com/T32266

components: Fix margins of search buttons

---

packages/eos-components/src/styles.scss

https://phabricator.endlessm.com/T32267

theme: Switch colors Read and Practice

---

kolibri_explore_plugin/assets/src/customApps.js
packages/template-ui/channel-overrides/oceanx/options.json
packages/template-ui/src/components/FilterResult.vue
packages/template-ui/src/store/index.js
packages/template-ui/src/views/Home.vue
packages/template-ui/src/views/ListSection.vue

https://phabricator.endlessm.com/T32278

T32278 flat

---

kolibri_explore_plugin/assets/src/views/SearchPage.vue
packages/eos-components/src/components/ChannelCard.vue
packages/eos-components/src/components/ChannelCardGroup.vue
packages/eos-components/src/components/CollapsibleCardGrid.vue
packages/eos-components/src/components/GridPage.vue

https://phabricator.endlessm.com/T32248

T32248 search results by type

---

kolibri_explore_plugin/assets/src/views/AboutModal.vue
kolibri_explore_plugin/assets/src/views/DiscoveryFooter.vue
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
packages/eos-components/src/styles.scss

https://phabricator.endlessm.com/T32283

T32283 about modal

---

packages/template-ui/channel-overrides/terminal-two/options.json

https://phabricator.endlessm.com/T32289

overrides: Terminal Two: Apply flat option

---

kolibri_explore_plugin/assets/src/views/SearchPage.vue
packages/eos-components/src/components/CollapsibleCardGrid.vue
packages/template-ui/src/views/ListSection.vue
packages/template-ui/src/views/Search.vue

In all remaining cases.
https://phabricator.endlessm.com/T32151

template: Replace paginated grid with collapsible variant

---

packages/eos-components/src/components/GridPage.vue

https://phabricator.endlessm.com/T32248

components: GridPage, de-hardcode transition

---

kolibri_explore_plugin/assets/src/customApps.js
packages/template-ui/channel-overrides/blockly-games/options.json

Blockly games will also have the flat-grid style applied.
https://phabricator.endlessm.com/T32287

channel-overrides: add one for Blockly Games

---

kolibri_explore_plugin/assets/src/customApps.js
packages/template-ui/channel-overrides/blockly-games/options.json
packages/template-ui/channel-overrides/cspathshala/options.json
packages/template-ui/channel-overrides/open-stax/options.json
packages/template-ui/channel-overrides/phet-interactive-simulations/options.json
packages/template-ui/channel-overrides/ted-ed-lessons/options.json
packages/template-ui/channel-overrides/thoughtful-learning/options.json

https://phabricator.endlessm.com/T32289

T32289 overrides

---

packages/template-ui/src/components/FilterContent.vue

https://phabricator.endlessm.com/T32232

components: Clear filter when the section changes

---

packages/eos-components/src/components/PlayButton.vue

https://phabricator.endlessm.com/T32304

T32304 icons

---

packages/eos-components/src/components/PlayButton.vue

https://phabricator.endlessm.com/T32145

components: PlayButton: Fix vertical alignment

---

kolibri_explore_plugin/assets/src/views/ContentModal.vue

https://phabricator.endlessm.com/T32300

ContentModal: Set dark color to content text

---

kolibri_explore_plugin/assets/src/views/SearchPage.vue

https://phabricator.endlessm.com/T32305

T32305 search order

---

packages/eos-components/src/styles.scss

Swith from darker variant to lighter.
https://phabricator.endlessm.com/T32321

theme: Use lighter variant in media buttons

---

packages/eos-components/src/components/Header.vue

Move the padding from the navbar to the container. Also clean unused
CSS rules.
https://phabricator.endlessm.com/T32279

components: Header: Fix logo alignment

---

packages/eos-components/src/components/ContentCard.vue
packages/eos-components/src/components/TopicCard.vue
packages/eos-components/src/components/mixins/cardMixin.js
packages/eos-components/src/styles.scss

https://phabricator.endlessm.com/T32325

T32325 low q thumbs

---

packages/eos-components/src/styles.scss

To avoid tag badges to be cropped.
https://phabricator.endlessm.com/T32291

theme: Tweak card body height

---

packages/template-ui/src/components/ChannelHeader.vue

By adding bottom margin.
https://phabricator.endlessm.com/T32294

template: Header: Fix Show more/less button being cut

---

packages/eos-components/src/components/ChannelCard.vue

If the description exceeds 3 lines.
https://phabricator.endlessm.com/T32343

components: ChannelCard: ellipsize description

---

kolibri_explore_plugin/assets/src/constants.js
kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js

https://phabricator.endlessm.com/T32347

T32347 carousel content

---

packages/eos-components/src/components/SearchBar.vue

Use icons from the Material Design library. Also, use primary color
for the close button.
https://phabricator.endlessm.com/T32296

components: SearchBar: Use Material icons

---

kolibri_explore_plugin/assets/src/apiResources.js
kolibri_explore_plugin/assets/src/customApps.js
kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
kolibri_explore_plugin/viewsets.py

https://phabricator.endlessm.com/T32370

T32370 carousel

---

packages/template-ui/channel-overrides/reading/options.json

https://phabricator.endlessm.com/T32253

Overrides: reading should have a white font in the header

---

kolibri_explore_plugin/assets/src/apiResources.js
kolibri_explore_plugin/assets/src/constants.js
kolibri_explore_plugin/assets/src/customApps.js
kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue
kolibri_explore_plugin/viewsets.py
packages/kolibri-api/index.js
packages/template-ui/channel-overrides/career-girls/options.json
packages/template-ui/src/App.vue
packages/template-ui/src/store/index.js

T32306 big channels

---

packages/loading-screen/src/App.vue

https://phabricator.endlessm.com/T32377

loading: Improve error messages

---

kolibri_explore_plugin/assets/src/constants.js
kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
kolibri_explore_plugin/assets/src/views/SearchPage.vue

Create a query for each media type that we're showing to group in the
backend instead of in the frontend.
https://phabricator.endlessm.com/T32391

Discovery: Improve search performance

---

packages/kolibri-api/index.js

https://phabricator.endlessm.com/T32349

Discovery: Show default thumbnails on search

---

kolibri_explore_plugin/assets/src/views/AboutModal.vue

https://phabricator.endlessm.com/T32404

Discovery: Set About dialog title and description

---

kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue
packages/eos-components/src/components/Card.vue
packages/kolibri-api/index.js
packages/template-ui/src/App.vue
packages/template-ui/src/store/index.js

T32306 loading

---

kolibri_explore_plugin/assets/src/customApps.js

https://phabricator.endlessm.com/T32401

Content: update to our custom Career Girls and TED-Ed channel

---

packages/eos-components/src/components/Carousel.vue
packages/eos-components/src/components/CarouselCard.vue

https://phabricator.endlessm.com/T32346

Components: Add shadow and hover effect to Carousel

---

packages/eos-components/src/components/CardBody.vue
packages/eos-components/src/utils.js
packages/template-ui/src/components/ChannelHeader.vue
packages/template-ui/src/store/index.js
packages/template-ui/src/store/modules/filters.js
packages/template-ui/src/views/Content.vue
packages/template-ui/src/views/Test.vue
yarn.lock

T32306 skip parsing

---

kolibri_explore_plugin/assets/src/customApps.js
packages/template-ui/channel-overrides/khan-academy/options.json

overrides: Add Khan Academy override to remove filters

---

kolibri_explore_plugin/assets/src/views/AboutModal.vue

https://phabricator.endlessm.com/T32308

Discovery: Add credits information

---

kolibri_explore_plugin/assets/src/constants.js
kolibri_explore_plugin/assets/src/views/SearchPage.vue
packages/eos-components/src/components/ButtonsBar.vue
packages/loading-screen/src/App.vue
packages/template-ui/src/components/ChannelFooter.vue
packages/template-ui/src/components/EmptyResultsMessage.vue
packages/template-ui/src/views/Search.vue

https://phabricator.endlessm.com/T32403

T32403 text edits

---

kolibri_explore_plugin/assets/src/customApps.js
packages/template-ui/channel-overrides/49ers-edu-digital-playbook/options.json
packages/template-ui/channel-overrides/49ers-edu-digital-playbook/styles.scss

Colors from: https://phabricator.endlessm.com/T32419
Override options:
- is simple bundle.
https://phabricator.endlessm.com/T32427

overrides: Add SF 49ers override

---

kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
kolibri_explore_plugin/assets/src/views/SearchPage.vue

https://phabricator.endlessm.com/T32416

discovery page: Capitalize channels

---

kolibri_explore_plugin/assets/src/customApps.js
packages/template-ui/channel-overrides/career-girls/styles.scss
packages/template-ui/channel-overrides/common-sense-student-resources/styles.scss
packages/template-ui/channel-overrides/sikana-diy/styles.scss
packages/template-ui/channel-overrides/techbridge-girls-home/styles.scss
packages/template-ui/channel-overrides/ted-ed-lessons/styles.scss

https://phabricator.endlessm.com/T32419

T32419 more colors

---

kolibri_explore_plugin/assets/src/customApps.js

In a7d348ba only the folders were removed. But we need to also remove
the entries from the `customApps.js` file.
https://phabricator.endlessm.com/T32419

overrides: Finish reverting last minute overrides

---

kolibri_explore_plugin/assets/src/modules/topicsTree/index.js
kolibri_explore_plugin/assets/src/routes/index.js
kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue
kolibri_explore_plugin/kolibri_plugin.py
kolibri_explore_plugin/options.py
packages/template-ui/src/App.vue
packages/template-ui/src/components/ChannelNavBar.vue
packages/template-ui/src/store/index.js

https://phabricator.endlessm.com/T32487

T32487 standalone channel

---

packages/template-ui/package.json
packages/template-ui/src/App.vue
packages/template-ui/src/components/Breadcrumb.vue
packages/template-ui/src/components/ChannelHeader.vue
packages/template-ui/src/components/ChannelNavBar.vue
packages/template-ui/src/components/MainSections.vue
packages/template-ui/src/components/mixins/headerMixin.js
packages/template-ui/src/store/index.js
packages/template-ui/src/utils.js
packages/template-ui/src/views/Content.vue
packages/template-ui/src/views/Home.vue
packages/template-ui/src/views/ListSection.vue
packages/template-ui/src/views/Search.vue
packages/template-ui/src/views/Section.vue
yarn.lock

https://phabricator.endlessm.com/T32534

T32534 breadcrumbs

---

packages/template-ui/src/views/Search.vue

This change is related to the following PR: https://github.com/endlessm/kolibri/pull/5
https://phabricator.endlessm.com/T32511

Search: Remove the "under" option

---

packages/template-ui/src/views/Home.vue

This change uses the WIP API change done in this PR: https://github.com/endlessm/kolibri/pull/4
https://phabricator.endlessm.com/T32513

Get carousel random content from kolibri API

---

packages/template-ui/src/App.vue
packages/template-ui/src/views/Home.vue

https://phabricator.endlessm.com/T32561

T32561 only topics

---

kolibri_explore_plugin/assets/src/customApps.js

https://phabricator.endlessm.com/T32553

CustomApps: point to newly curated Techbridge Girls channel

---

packages/eos-components/src/components/CarouselCard.vue
packages/eos-components/src/components/ContentCard.vue
packages/eos-components/src/components/mixins/cardMixin.js
packages/kolibri-api/index.js
packages/template-ui/src/components/ContentImage.vue
packages/template-ui/src/views/BundleSection.vue
packages/template-ui/src/views/Content.vue
packages/template-ui/src/views/Home.vue

https://phabricator.endlessm.com/T32533

T32533 clean thumbs

---

packages/template-ui/src/App.vue

https://phabricator.endlessm.com/T32572

Get the channel metadata from API

---

.github/workflows/lint.yml
packages/template-ui/src/App.vue
packages/template-ui/src/components/Breadcrumb.vue
packages/template-ui/src/components/ChannelFooter.vue
packages/template-ui/src/components/ChannelHeader.vue
packages/template-ui/src/store/index.js
packages/template-ui/src/views/BundleSection.vue
packages/template-ui/src/views/Content.vue
packages/template-ui/src/views/Home.vue

https://phabricator.endlessm.com/T32512

T32512 flat

---

packages/eos-components/src/components/CardGrid.vue
packages/eos-components/src/components/CollapsibleCardGrid.vue
packages/eos-components/src/components/SlidableCardGrid.vue
packages/eos-components/src/constants.js
packages/template-ui/src/components/FilterResult.vue
packages/template-ui/src/views/Home.vue

https://phabricator.endlessm.com/T32608

Load content by demand on SlidableCardGrid

---

packages/template-ui/src/components/FilterResult.vue
packages/template-ui/src/views/BundleSection.vue
packages/template-ui/src/views/Home.vue
packages/template-ui/src/views/ListSection.vue
packages/template-ui/src/views/Section.vue

https://phabricator.endlessm.com/T32573

Update api migration

---

kolibri_explore_plugin/assets/src/views/AssessmentWrapper/ExerciseAttempts/AnswerIcon.vue
kolibri_explore_plugin/assets/src/views/AssessmentWrapper/ExerciseAttempts/index.vue
kolibri_explore_plugin/assets/src/views/AssessmentWrapper/LessonMasteryBar.vue
kolibri_explore_plugin/assets/src/views/AssessmentWrapper/OverallStatus.vue
kolibri_explore_plugin/assets/src/views/AssessmentWrapper/index.vue

https://phabricator.endlessm.com/T32759

Update assesment wrapper

---

kolibri_explore_plugin/assets/src/kolibriApi.js
packages/template-ui/src/components/FilterResult.vue
packages/template-ui/src/views/BundleSection.vue
packages/template-ui/src/views/Home.vue
packages/template-ui/src/views/ListSection.vue
packages/template-ui/src/views/Section.vue

https://phabricator.endlessm.com/T32761

Fix filter 0.15

---

kolibri_explore_plugin/assets/src/kolibriApi.js
packages/template-ui/src/components/FilterResult.vue

This change adapts the API to the changes upstream in this PR:
https://github.com/learningequality/kolibri/pull/8796
https://phabricator.endlessm.com/T32761

template: Use descendant_of filter

---

README.md
docs/template-spec.md
docs/template-tech-info.md

https://phabricator.endlessm.com/T32800

T32800 template and bundling docs

---

kolibri_explore_plugin/assets/src/kolibriApi.js
packages/template-ui/src/components/FilterResult.vue
packages/template-ui/src/views/Home.vue
packages/template-ui/src/views/ListSection.vue
packages/template-ui/src/views/Section.vue

https://phabricator.endlessm.com/T32767

API: Add query context to the pagination object

---

kolibri_explore_plugin/assets/package.json
kolibri_explore_plugin/assets/src/composables/useContentNodeProgress.js
kolibri_explore_plugin/assets/src/composables/useProgressTracking.js
kolibri_explore_plugin/assets/src/views/AssessmentWrapper/index.vue
kolibri_explore_plugin/assets/src/views/ContentItem.vue
yarn.lock

https://phabricator.endlessm.com/T32831

Update content item

---

kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
kolibri_explore_plugin/assets/src/views/SearchPage.vue
packages/eos-components/src/components/NavBar.vue
packages/eos-components/src/index.scss
packages/eos-components/src/main.js
packages/eos-components/src/styles.scss
packages/template-ui/package.json
packages/template-ui/src/components/Breadcrumb.vue
packages/template-ui/src/components/ChannelHeader.vue
packages/template-ui/src/components/ChannelNavBar.vue
packages/template-ui/src/components/mixins/headerMixin.js

https://phabricator.endlessm.com/T32921

T32921 channel navigation

---

packages/template-ui/src/components/ChannelHeader.vue
packages/template-ui/src/components/DetailView.vue
packages/template-ui/src/views/BundleSection.vue
packages/template-ui/src/views/Content.vue

https://phabricator.endlessm.com/T32923

T32923 back button 2

---

packages/eos-components/src/components/PlayButton.vue
packages/template-ui/src/components/ContentImage.vue
packages/template-ui/src/views/BundleSection.vue
packages/template-ui/src/views/Content.vue

https://phabricator.endlessm.com/T32916

Improve detail page

---

kolibri_explore_plugin/assets/src/constants.js
kolibri_explore_plugin/assets/src/modules/coreExplore/mutations.js
kolibri_explore_plugin/assets/src/modules/pluginModule.js
kolibri_explore_plugin/assets/src/routes/index.js
kolibri_explore_plugin/assets/src/views/ContentPage.vue
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
packages/eos-components/src/styles.scss
packages/template-ui/channel-overrides/wikipedia/components/DetailView.vue
packages/template-ui/channel-overrides/wikipedia/options.json
packages/template-ui/channel-overrides/wikipedia/styles.scss
packages/template-ui/src/App.vue
packages/template-ui/src/store/index.js
packages/template-ui/src/views/Content.vue
packages/template-ui/src/views/Home.vue

https://phabricator.endlessm.com/T32928

Display zim full iframe

---

.pre-commit-config.yaml
yarn.lock

https://phabricator.endlessm.com/T32951
https://github.blog/2021-09-01-improving-git-protocol-security-github/

CI: Fix problems installing dependencies

---

kolibri_explore_plugin/assets/src/views/DevTag.vue

https://phabricator.endlessm.com/T32946

Discovery: Don't show debug info in iframes

---

packages/eos-components/src/components/PlayButton.vue
packages/eos-components/src/index.scss
packages/template-ui/src/components/FilterContent.vue
packages/template-ui/src/components/FilterDropDown.vue
packages/template-ui/src/components/MediaFilterButtons.vue
packages/template-ui/src/views/ListSection.vue

https://phabricator.endlessm.com/T32931

template: Update channel filter component

---

packages/eos-components/src/components/Card.vue
packages/eos-components/src/components/CardBody.vue
packages/eos-components/src/components/ContentCard.vue
packages/eos-components/src/components/TopicCard.vue

The new Card component has the description as subtitle, and the author
information just when isEndlessApp.
The TopicCard goes with the subtitle and a new badge at bottom.
All tags are removed from cards.
https://phabricator.endlessm.com/T32924

component: Update Card components

---

packages/template-ui/src/components/FilterContent.vue
packages/template-ui/src/components/FilterResult.vue

This reverts commit a19f2519de77ecab0fecdf071841b498670156c7.
https://phabricator.endlessm.com/T32838

Revert "filter: Remove StructuredTags filtering"

---

packages/eos-components/src/components/CarouselCard.vue
packages/eos-components/src/components/CarouselCardTitle.vue
packages/eos-components/src/main.js

The new CarouselCard component has the description as subtitle, and the
author information just when isEndlessApp.
https://phabricator.endlessm.com/T32926

component: Update CarouselCard components

---

kolibri_explore_plugin/assets/src/views/SearchPage.vue
packages/eos-components/src/components/SearchBar.vue

https://phabricator.endlessm.com/T32917
This PR depends on this one https://github.com/endlessm/kolibri-explore-plugin/pull/327, that adds the `Keyword` component.

Update discovery search

---

packages/eos-components/src/components/CardGrid.vue
packages/eos-components/src/components/SlidableCardGrid.vue
packages/eos-components/src/index.scss
packages/eos-components/src/styles.scss
packages/template-ui/src/views/Search.vue

https://phabricator.endlessm.com/T32927

T32927 row of cards

---

kolibri_explore_plugin/assets/src/customApps.js
packages/template-ui/channel-overrides/wikihow-arts-and-entertainment/components/Breadcrumb.vue
packages/template-ui/channel-overrides/wikihow-arts-and-entertainment/components/DetailView.vue
packages/template-ui/channel-overrides/wikihow-arts-and-entertainment/options.json
packages/template-ui/channel-overrides/wikihow-arts-and-entertainment/styles.scss
packages/template-ui/channel-overrides/wikihow-computers-and-electronics/components/Breadcrumb.vue
packages/template-ui/channel-overrides/wikihow-computers-and-electronics/components/DetailView.vue
packages/template-ui/channel-overrides/wikihow-computers-and-electronics/options.json
packages/template-ui/channel-overrides/wikihow-computers-and-electronics/styles.scss
packages/template-ui/channel-overrides/wikihow-hobbies-and-crafts/components/Breadcrumb.vue
packages/template-ui/channel-overrides/wikihow-hobbies-and-crafts/components/DetailView.vue
packages/template-ui/channel-overrides/wikihow-hobbies-and-crafts/options.json
packages/template-ui/channel-overrides/wikihow-hobbies-and-crafts/styles.scss

https://phabricator.endlessm.com/T33008

Add custom presentation for individual category based wikiHow channels

---

packages/eos-components/src/components/SlidableCardGrid.vue
packages/template-ui/src/components/SectionTitle.vue

https://phabricator.endlessm.com/T32927

T32927 icons alt

---

packages/template-ui/src/components/Breadcrumb.vue
packages/template-ui/src/components/ChannelNavBar.vue
packages/template-ui/src/router/index.js

https://phabricator.endlessm.com/T33025

template: Clear filters on going home from Breadcrumb

---

kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue
kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
packages/eos-components/src/components/BackToTop.vue
packages/eos-components/src/components/ChannelCard.vue
packages/eos-components/src/styles.scss
packages/template-ui/src/components/EmptyResultsMessage.vue
packages/template-ui/src/components/FilterContent.vue
packages/template-ui/src/components/FilterDropDown.vue
packages/template-ui/src/components/MainSections.vue
packages/template-ui/src/components/MediaFilterButtons.vue
packages/template-ui/src/components/SectionsSearchRow.vue
packages/template-ui/src/views/Content.vue
packages/template-ui/src/views/Search.vue

https://phabricator.endlessm.com/T33033

T33033 livecoding

---

kolibri_explore_plugin/assets/src/components/ChannelsList.vue
kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
kolibri_explore_plugin/assets/src/views/SearchPage.vue

https://phabricator.endlessm.com/T33030

T33030 channels list

---

packages/template-ui/channel-overrides/wikihow/options.json

https://phabricator.endlessm.com/T32799

Update default content node for WikiHow

---

kolibri_explore_plugin/assets/src/customApps.js
packages/template-ui/channel-overrides/wikihow-cars-and-other-vehicles/options.json
packages/template-ui/channel-overrides/wikihow-cars-and-other-vehicles/styles.scss
packages/template-ui/channel-overrides/wikihow-education-and-communications/options.json
packages/template-ui/channel-overrides/wikihow-education-and-communications/styles.scss
packages/template-ui/channel-overrides/wikihow-food-and-entertaining/options.json
packages/template-ui/channel-overrides/wikihow-food-and-entertaining/styles.scss
packages/template-ui/channel-overrides/wikihow-holidays-and-traditions/options.json
packages/template-ui/channel-overrides/wikihow-holidays-and-traditions/styles.scss
packages/template-ui/channel-overrides/wikihow-home-and-garden/options.json
packages/template-ui/channel-overrides/wikihow-home-and-garden/styles.scss
packages/template-ui/channel-overrides/wikihow-personal-care-and-style/options.json
packages/template-ui/channel-overrides/wikihow-personal-care-and-style/styles.scss
packages/template-ui/channel-overrides/wikihow-sports-and-fitness/options.json
packages/template-ui/channel-overrides/wikihow-sports-and-fitness/styles.scss
packages/template-ui/channel-overrides/wikihow-work-world/options.json
packages/template-ui/channel-overrides/wikihow-work-world/styles.scss
packages/template-ui/channel-overrides/wikihow-youth/options.json
packages/template-ui/channel-overrides/wikihow-youth/styles.scss

https://phabricator.endlessm.com/T33064

Add overrides for WikiHow category channels

---

packages/eos-components/src/components/CardGridPlaceholder.vue
packages/template-ui/src/views/Content.vue
packages/template-ui/src/views/Home.vue
packages/template-ui/src/views/ListSection.vue

https://phabricator.endlessm.com/T33072

template: Remove row wrapper for heading

---

packages/template-ui/src/components/ChannelNavBar.vue

https://phabricator.endlessm.com/T33036

template: Show channel logo always in the topbar

---

packages/template-ui/src/components/BackButton.vue
packages/template-ui/src/components/ChannelHeader.vue
packages/template-ui/src/components/DetailView.vue

Add a new component for the template Back Button. This patch also
modifies the default positioning of this new button to place it on the
left margin of the header.
https://phabricator.endlessm.com/T33081

template: New BackButton component

---

packages/template-ui/src/components/BackButton.vue
packages/template-ui/src/components/ChannelHeader.vue

https://phabricator.endlessm.com/T33081

template: Support dark background in BackButton

---

kolibri_explore_plugin/assets/src/components/AboutModal.vue

https://phabricator.endlessm.com/T32974

Discovery: Fix the support link in about dialog

---

packages/template-ui/src/components/ContentImage.vue
packages/template-ui/src/components/DetailView.vue
packages/template-ui/src/styles.scss
packages/template-ui/src/views/BundleSection.vue
packages/template-ui/src/views/Content.vue

https://phabricator.endlessm.com/T32942

Polish detail page

---

kolibri_explore_plugin/assets/src/kolibriApi.js
packages/template-ui/src/views/Home.vue

https://phabricator.endlessm.com/T33091

T33091 bring back random highlights

---

kolibri_explore_plugin/assets/src/constants.js

https://phabricator.endlessm.com/T33125

Discovery: SEARCH_MAX_RESULTS to 32

---

kolibri_explore_plugin/assets/src/customApps.js
packages/template-ui/channel-overrides/coronavirus/options.json
packages/template-ui/channel-overrides/coronavirus/styles.scss
packages/template-ui/channel-overrides/khan-academy/options.json
packages/template-ui/channel-overrides/open-stax/options.json
packages/template-ui/channel-overrides/phet-interactive-simulations/options.json
packages/template-ui/channel-overrides/ted-ed-lessons/options.json
packages/template-ui/channel-overrides/thoughtful-learning/options.json
packages/template-ui/src/store/index.js
packages/template-ui/src/views/Home.vue

https://phabricator.endlessm.com/T33129

T33129 carousel curation

---

packages/template-ui/src/components/SectionsSearchRow.vue

https://phabricator.endlessm.com/T33060

template: Use material icon in SectionsSearchRow

---

packages/template-ui/src/components/SectionsSearchRow.vue

https://phabricator.endlessm.com/T33060

Template: Set MagnifyIcon size to KeywordIconSize

---

kolibri_explore_plugin/assets/src/components/AboutModal.vue
kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
kolibri_explore_plugin/assets/src/views/SearchPage.vue

https://phabricator.endlessm.com/T33145

Fix about modal

---

packages/template-ui/channel-overrides/pbs-kids/components/ChannelHeader.vue
packages/template-ui/channel-overrides/pbs-kids/styles.scss

https://phabricator.endlessm.com/T32950

template: Same breadcrumb styles for pbs-kids

---

kolibri_explore_plugin/assets/src/views/SearchPage.vue

Initialize query when the component is created. We already have a
watcher for the next changes.
https://phabricator.endlessm.com/T33195

Discovery: Fix initial query in SearchPage

---

kolibri_explore_plugin/assets/src/components/AboutModal.vue

https://phabricator.endlessm.com/T32974

Discovery: Fix link to Support site in About modal

---

kolibri_explore_plugin/assets/src/components/AboutModal.vue

https://phabricator.endlessm.com/T33198

Discovery: Open support link in default browser

---

packages/template-ui/src/views/BundleSection.vue

https://phabricator.endlessm.com/T33222

template: Make bundles description 50% wide

---

kolibri_explore_plugin/assets/src/customApps.js

The new channel does have better quality Ebooks in suitable languages.
https://phabricator.endlessm.com/T33206

channel overrides: switch to new Chapter Books channel

---

packages/eos-components/src/components/SearchBar.vue

Focus the input when the user clicks on the X button to clear it.
https://phabricator.endlessm.com/T33199

components: SearchBar: focus on clear

---

kolibri_explore_plugin/assets/src/views/SearchPage.vue

https://phabricator.endlessm.com/T33203

Discovery: Update url params on keyword removed

---

scripts/review_highlighted.py

https://phabricator.endlessm.com/T33090

scripts: Add script to review the highlighted IDs

---

kolibri_explore_plugin/assets/src/app.js

https://phabricator.endlessm.com/T33246

electron: Emit resize event after fullscreen

---

scripts/review_highlighted.py

- Use fetchone instead of fetchall as @dylan commented in the PR
- Add option to print all found titles / IDs
https://phabricator.endlessm.com/T33258

scripts: Improve review highlighted script

---

README.md
scripts/check_can_relese.sh

Add a note in the README, and change the check script.
https://phabricator.endlessm.com/T33270

scripts: Use the stable branch for releasing

---

.github/workflows/lint.yml
.github/workflows/node.yml
.github/workflows/release-apps.yml
dependency-stub/index.js
dependency-stub/package.json
kolibri_explore_plugin/assets/package.json
package.json
scripts/bootstrap.sh
yarn.lock

Remove almost all dependabot warnings forcing package versions in "resolutions".
Also updates the node engine to 16.x
https://phabricator.endlessm.com/T33280

Update js deps

---

kolibri_explore_plugin/assets/src/customApps.js
kolibri_explore_plugin/assets/src/searchApi.js
kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue
kolibri_explore_plugin/assets/src/views/SearchPage.vue
packages/eos-components/src/components/ContentCard.vue
packages/template-ui/src/components/DetailViewFullScreen.vue

Iterates over all the defined ZimSearchChannels and look for all the zim
content nodes to search for articles there. To search it's used the
kolibri-zim-plugin JSON API.
https://phabricator.endlessm.com/T33078

Discovery: Initial search inside the zim files

---

.pre-commit-config.yaml
package.json
scripts/create_mock_nodes.py
yarn.lock

https://phabricator.endlessm.com/T33351

Add kolibri-design-system resolution to package.json

---

kolibri_explore_plugin/options.py
kolibri_explore_plugin/views.py

https://phabricator.endlessm.com/T33411

Add an option to load channel apps from elsewhere

---

package.json
yarn.lock

To fix the build, target the commit from Github for release tag v1.3.0.
https://phabricator.endlessm.com/T33412

package.json: Update kolibri-design-system version

---

kolibri_explore_plugin/assets/src/components/InstallContentModal.vue
kolibri_explore_plugin/assets/src/modules/coreExplore/actions.js
kolibri_explore_plugin/assets/src/modules/coreExplore/mutations.js
kolibri_explore_plugin/assets/src/modules/pluginModule.js
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
kolibri_explore_plugin/urls.py
kolibri_explore_plugin/views.py

https://phabricator.endlessm.com/T33342

Add EndlessLearningCollection view

---

kolibri_explore_plugin/api_urls.py
kolibri_explore_plugin/assets/src/modules/coreExplore/actions.js
kolibri_explore_plugin/assets/src/modules/coreExplore/mutations.js
kolibri_explore_plugin/assets/src/modules/pluginModule.js
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
kolibri_explore_plugin/kolibri_plugin.py
kolibri_explore_plugin/urls.py
kolibri_explore_plugin/views.py
packages/eos-components/src/components/CollectionSelectionModal.vue
packages/eos-components/src/components/InstallContentModal.vue
packages/eos-components/src/main.js

https://phabricator.endlessm.com/T33571

discovery: Add collection selection dialog

---

packages/loading-screen/src/App.vue
packages/loading-screen/src/views/EndlessKey.vue
packages/loading-screen/src/views/Welcome.vue

https://phabricator.endlessm.com/T33565

Wire webpage

---

kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
kolibri_explore_plugin/views.py
packages/eos-components/src/components/InstallContentModal.vue
packages/eos-components/src/constants.js

https://phabricator.endlessm.com/T33482

Show InstallContentModal if there running jobs

---

packages/loading-screen/public/index.html
packages/template-ui/public/index.html

https://phabricator.endlessm.com/T33562

Template, loading screen: Ensure light theme

---

kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
kolibri_explore_plugin/views.py
packages/eos-components/src/components/CollectionSelectionModal.vue
packages/eos-components/src/index.scss

Disable collections that are bigger than the space available so the user
can't try to install a collection if there's no enought space.
https://phabricator.endlessm.com/T33572

Detect available space in device

---

kolibri_explore_plugin/views.py

https://phabricator.endlessm.com/T33571

Update placeholder collections

---

kolibri_explore_plugin/assets/src/components/CategorizedChannelsList.vue
kolibri_explore_plugin/assets/src/components/CategorizedList.vue
kolibri_explore_plugin/assets/src/customApps.js
kolibri_explore_plugin/assets/src/views/DiscoveryPage.vue
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue

https://phabricator.endlessm.com/T33654

T33654 discovery redesign

---

packages/loading-screen/src/views/Loading.vue

https://phabricator.endlessm.com/T33585

loading: Drop user guide link

---

packages/loading-screen/src/styles.scss

https://phabricator.endlessm.com/T33683

Increment inner-container-max-width to 900px

---

kolibri_explore_plugin/views.py
packages/eos-components/src/components/InstallContentModal.vue

https://phabricator.endlessm.com/T33697

Fix progress bar back and forth behavior

---

packages/eos-components/src/components/GradeSelectionModal.vue

https://phabricator.endlessm.com/T33669

Remove card columns in GradeSelectionModal on small screens

---

kolibri_explore_plugin/views.py
packages/eos-components/src/components/InstallContentModal.vue

https://phabricator.endlessm.com/T33697

discovery: handle failed jobs in InstallContentModal

---

packages/loading-screen/src/App.vue
packages/loading-screen/src/main.js
packages/loading-screen/src/views/PermissionsWrongFolder.vue

https://phabricator.endlessm.com/T33711

loading: Add initial permission wrong folder view

---

kolibri_explore_plugin/assets/src/components/AboutModal.vue
kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue
packages/loading-screen/src/styles.scss
packages/loading-screen/src/views/ContentSourceSelection.vue
packages/loading-screen/src/views/Loading.vue
packages/loading-screen/src/views/PermissionsCancelled.vue
packages/loading-screen/src/views/PermissionsExplanation.vue
packages/loading-screen/src/views/PermissionsWrongFolder.vue
packages/loading-screen/src/views/UsbDriveConnection.vue
packages/loading-screen/src/views/Welcome.vue
packages/loading-screen/src/views/WelcomeBase.vue

Except when referred to something like: "the Endless Key initiative"
https://phabricator.endlessm.com/T33672

wording: Remove "the" Endless Key

---

packages/eos-components/src/components/CollectionSelectionModal.vue
packages/eos-components/src/components/GradeSelectionModal.vue
packages/eos-components/src/components/WelcomeCard.vue
packages/loading-screen/src/App.vue
packages/loading-screen/src/main.js
packages/loading-screen/src/views/ContentSourceSelection.vue
packages/loading-screen/src/views/Loading.vue
packages/loading-screen/src/views/LoadingError.vue
packages/loading-screen/src/views/LoadingInitial.vue
packages/loading-screen/src/views/LoadingRetry.vue
packages/loading-screen/src/views/PermissionsCancelled.vue
packages/loading-screen/src/views/PermissionsWrongFolder.vue
packages/loading-screen/src/views/UsbDriveConnection.vue
packages/loading-screen/src/views/Welcome.vue
packages/loading-screen/src/views/WelcomeBase.vue

- Content source selection view: Update secondary text
- Loading view: Update secondary text
- Change "check your..." for "view your..." download choices
- USB drive connection view: Move secondary text to image alt.
- Welcome view: add period to secondary text.
https://phabricator.endlessm.com/T33672

Welcome screen: More text edits

---

packages/loading-screen/src/main.js
packages/loading-screen/src/views/ContentSourceSelection.vue
packages/loading-screen/src/views/PermissionsCancelled.vue
packages/loading-screen/src/views/PermissionsExplanation.vue
packages/loading-screen/src/views/PermissionsWrongFolder.vue
packages/loading-screen/src/views/UsbDriveConnection.vue

https://phabricator.endlessm.com/T33672

T33672 welcome polish

---

kolibri_explore_plugin/assets/src/components/InstallContentModal.vue
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue

https://phabricator.endlessm.com/T33760

Improve download progressbar

---

kolibri_explore_plugin/assets/src/modules/topicsTree/handlers.js
kolibri_explore_plugin/kolibri_plugin.py
kolibri_explore_plugin/views.py

https://phabricator.endlessm.com/T33793

Rebase kolibri 016

---

kolibri_explore_plugin/assets/package.json
kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue
kolibri_explore_plugin/assets/src/views/AssessmentWrapper/index.vue
package.json
packages/eos-components/package.json
packages/eos-components/src/components/ChannelCard.vue
packages/eos-components/src/components/SlidableGrid.vue
packages/eos-components/src/styles.scss
packages/loading-screen/package.json
packages/template-ui/package.json
yarn.lock

https://phabricator.endlessm.com/T33793

T33793 javascript dependencies

---

kolibri_explore_plugin/api_urls.py
kolibri_explore_plugin/assets/package.json
kolibri_explore_plugin/assets/src/components/InstallContentModal.vue
kolibri_explore_plugin/assets/src/constants.js
kolibri_explore_plugin/assets/src/modules/topicsTree/handlers.js
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
kolibri_explore_plugin/collectionviews.py
kolibri_explore_plugin/views.py
yarn.lock

This is the backend part of the reimplementation.
https://phabricator.endlessm.com/T33835

Reimplement download of collections - backend part

---

kolibri_explore_plugin/assets/src/views/CustomChannelPresentationApp.vue

https://phabricator.endlessm.com/T33948

Fix channel iframe loading before API is available

---

kolibri_explore_plugin/api_urls.py
kolibri_explore_plugin/assets/src/components/CollectionSelectionModal.vue
kolibri_explore_plugin/assets/src/components/GradeSelectionModal.vue
kolibri_explore_plugin/assets/src/components/InstallContentModal.vue
kolibri_explore_plugin/assets/src/modules/coreExplore/actions.js
kolibri_explore_plugin/assets/src/modules/coreExplore/mutations.js
kolibri_explore_plugin/assets/src/modules/pluginModule.js
kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
kolibri_explore_plugin/assets/src/views/DiscoveryPage.vue
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
kolibri_explore_plugin/collectionviews.py
kolibri_explore_plugin/views.py

https://phabricator.endlessm.com/T33835

Reimplement download of collections - frontend part

---

kolibri_explore_plugin/assets/src/views/DiscoveryPage.vue
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
kolibri_explore_plugin/collectionviews.py

https://phabricator.endlessm.com/T33835

T33835 download info logs

---

kolibri_explore_plugin/collectionviews.py

For when it's still going and for when it's completed
https://phabricator.endlessm.com/T33835

Download collections backend: Log job duration

---

kolibri_explore_plugin/assets/src/components/InstallContentModal.vue

According to the page visibility. Using the pageVisible core state.
https://phabricator.endlessm.com/T34158

Download content modal: pause/resume polling update

---

kolibri_explore_plugin/assets/src/components/AboutModal.vue
kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue
packages/eos-components/src/components/PrivacyPolicyText.vue
packages/eos-components/src/main.js
packages/loading-screen/src/App.vue
packages/loading-screen/src/views/ContentSourceSelection.vue
packages/loading-screen/src/views/PermissionsCancelled.vue
packages/loading-screen/src/views/PermissionsExplanation.vue
packages/loading-screen/src/views/PermissionsWrongFolder.vue
packages/loading-screen/src/views/UsbDriveConnection.vue
packages/loading-screen/src/views/Welcome.vue

https://phabricator.endlessm.com/T33905

T33905 privacy policy

---

packages/eos-components/src/components/PrivacyPolicyText.vue

https://phabricator.endlessm.com/T34219

Components: Improve policy text punctuation

---

kolibri_explore_plugin/api_urls.py
kolibri_explore_plugin/assets/src/apiResources.js
kolibri_explore_plugin/assets/src/components/CategorizedList.vue
kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue
kolibri_explore_plugin/assets/src/views/DiscoveryPage.vue
kolibri_explore_plugin/assets/src/views/DiscoveryPageCollections.vue
kolibri_explore_plugin/assets/src/views/DiscoveryPageFullContent.vue
kolibri_explore_plugin/assets/src/views/SearchPage.vue
kolibri_explore_plugin/kolibri_plugin.py
kolibri_explore_plugin/options.py
kolibri_explore_plugin/viewsets.py
packages/eos-components/src/components/CardGrid.vue
packages/eos-components/src/components/ChannelCard.vue
packages/eos-components/src/components/SlidableCardGrid.vue
packages/eos-components/src/components/SlidableGrid.vue
packages/eos-components/src/constants.js
packages/eos-components/src/utils.js
packages/template-ui/src/views/Home.vue
packages/template-ui/src/views/ListSection.vue

https://phabricator.endlessm.com/T34285

T34285 discovery collections

---

scripts/bootstrap.sh

To avoid the "yarn is out of date" warning.

Bump yarn to latest

---

MANIFEST.in

The setuptools build was missing these files.
https://phabricator.endlessm.com/T34472

Add migrations and management folders to build

---

kolibri_explore_plugin/assets/src/components/InstallContentModal.vue
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
kolibri_explore_plugin/collectionviews.py

https://phabricator.endlessm.com/T34466

T34466 single progress

---

kolibri_explore_plugin/assets/src/components/EkIguanaList.vue
kolibri_explore_plugin/assets/src/components/InstallContentModal.vue
kolibri_explore_plugin/assets/src/customApps.js
kolibri_explore_plugin/assets/src/views/DiscoveryPage.vue
kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue
kolibri_explore_plugin/assets/src/views/DiscoveryPageEkIguana.vue
kolibri_explore_plugin/assets/src/views/ExploreIndex.vue
kolibri_explore_plugin/collectionviews.py
kolibri_explore_plugin/kolibri_plugin.py
kolibri_explore_plugin/options.py

https://phabricator.endlessm.com/T34363

T34363 final hook

---

kolibri_explore_plugin/assets/src/components/InstallContentModal.vue
kolibri_explore_plugin/collectionviews.py

https://phabricator.endlessm.com/T34520

T34520 handle insufficient space

---

MANIFEST.in

https://phabricator.endlessm.com/T34548

Build: Remove collections from build

---

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
kolibri_explore_plugin/assets/src/modules/topicsTree/handlers.js

https://phabricator.endlessm.com/T34538

T34538 keep lights on

---

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js

https://phabricator.endlessm.com/T34543

Search: Don't add empty results to state

---

packages/template-ui/src/components/BackButton.vue

Check window.history because the VueJS router doesn't have the history list.
Also, add styling for the disabled state. Because this component isn't respecting our theme yet.
https://phabricator.endlessm.com/T34612

Template: Disable BackButton when no history

---

kolibri_explore_plugin/assets/src/views/ContentUnavailablePage.vue

Also: add minimum styling so it's centered as the welcome pages.
https://phabricator.endlessm.com/T34611

Explore: Add retry button to content unavailable

---

kolibri_explore_plugin/api_urls.py
kolibri_explore_plugin/assets/src/modules/coreExplore/utils.js
kolibri_explore_plugin/assets/src/views/DownloadPage.vue
kolibri_explore_plugin/collectionviews.py

By getting the browser current timezone, and checking if it's one of the US timezones.
https://phabricator.endlessm.com/T34589

Utils: Add function to check if user is in the US

---

kolibri_explore_plugin/assets/src/views/DownloadPage.vue

Call the temporary API to filter US content.
https://phabricator.endlessm.com/T34589

Frontend download: Set is US user before download

---

.github/workflows/lint.yml
.github/workflows/node.yml
.github/workflows/release-apps.yml

The previous version was deprecated:
https://github.com/actions/runner-images/issues/6002
https://phabricator.endlessm.com/T34666

Update github actions to run in ubuntu-latest

---

packages/welcome-screen/src/views/Loading.vue

https://phabricator.endlessm.com/T34639

Welcome: Remove "please wait" from Loading screen

---

kolibri_explore_plugin/api_urls.py
kolibri_explore_plugin/assets/src/modules/coreExplore/utils.js
kolibri_explore_plugin/assets/src/views/DownloadPage.vue
kolibri_explore_plugin/collectionviews.py

https://phabricator.endlessm.com/T34691

T34691 revert per region

---

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js

The long running caching is enabled in the channels resource by default. Disable it during the showChannels handler.
https://phabricator.endlessm.com/T34704

Download: Skip channels cache after download

---

kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue
kolibri_explore_plugin/assets/src/routes/index.js
kolibri_explore_plugin/kolibri_plugin.py
kolibri_explore_plugin/options.py

https://phabricator.endlessm.com/T34778

T34778 hide discovery

---

LICENSE
setup.py

~~I actually don't know where key@endlessos.org goes but it autocompletes in GMail and is more likely to work than danigm@endlessos.org.~~
key@ goes to our engineering team.

Add LICENSE and update author details

---

kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue
kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue

https://phabricator.endlessm.com/T34665

Landing page: Add feedback button

---

Pipfile
Pipfile.lock
README.md

The pipenv is a dependent tool for build/development. Add the description and the possible pip module error's solution relating to pipenv.

README: Add pipenv as the dependency in the Setup section

---

kolibri_explore_plugin/assets/src/apiResources.js
kolibri_explore_plugin/assets/src/components/AlphabeticalChannelsList.vue
kolibri_explore_plugin/assets/src/components/EkIguanaList.vue
kolibri_explore_plugin/assets/src/mixins/navigationMixin.js
kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue
kolibri_explore_plugin/assets/src/views/SearchPage.vue
kolibri_explore_plugin/viewsets.py
packages/ek-components/src/components/EkChannelCard.vue

Featured channels

---

kolibri_explore_plugin/assets/src/kolibriApi.js
kolibri_explore_plugin/assets/src/modules/coreExplore/actions.js
kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
kolibri_explore_plugin/assets/src/modules/topicsTree/handlers.js
kolibri_explore_plugin/kolibri_plugin.py
kolibri_explore_plugin/options.py

Navigate unavailable channels and content

---

kolibri_explore_plugin/assets/src/views/ContentUnavailablePage.vue
kolibri_explore_plugin/assets/src/views/DiscoveryPage.vue
kolibri_explore_plugin/assets/src/views/DownloadPage.vue
kolibri_explore_plugin/assets/src/views/SearchPage.vue

Closes [#551](https://github.com/endlessm/kolibri-explore-plugin/issues/551)

Add titles

---

packages/ek-components/src/components/EkCardBody.vue
packages/ek-components/src/components/EkCarouselCard.vue
packages/ek-components/src/components/EkContentCard.vue
packages/ek-components/src/components/EkContentLink.vue
packages/ek-components/src/components/EkPlayButton.vue
packages/ek-components/src/styles.scss
packages/template-ui/src/components/ContentImage.vue
packages/template-ui/src/components/MediaFilterButtons.vue

Starting with the easy bit:
Related: https://github.com/endlessm/kolibri-explore-plugin/issues/534

Various improvements to cards

---

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue
packages/ek-components/src/utils.js

Channel info

---

packages/template-ui/src/App.vue
packages/template-ui/src/mockKolibriApi.js
packages/template-ui/src/views/Test.vue

Bring back test page

---

packages/ek-components/src/components/EkCardBody.vue
packages/ek-components/src/index.scss
packages/ek-components/src/styles.scss

Theme changes

---

kolibri_explore_plugin/assets/package.json
kolibri_explore_plugin/assets/src/components/AboutModal.vue
yarn.lock

Bump kolibri tools

---

kolibri_explore_plugin/collectionviews.py

https://github.com/endlessm/kolibri-explore-plugin/issues/606

Download: Include "extras" collection

---

package.json
yarn.lock

To be the same as current Kolibri
Fixes #614

Bump webpack dependencies

---

package.json
yarn.lock

To be the same as Kolibri alpha15
Fixes #614

Bump webpack dependencies again

---

kolibri_explore_plugin/collectionviews.py

Here's a couple things I came across while working on #549. I decided to split them out instead of including them in that PR.

Import content cleanup

---

kolibri_explore_plugin/assets/src/modules/manageContent/handlers.js

https://github.com/endlessm/kolibri-explore-plugin/issues/632

handlers: Set download state to failed if task fails

---

kolibri_explore_plugin/assets/src/views/SearchPage.vue

Also adds internationalizaion to them.
Fixes #612

Search: Add prularisation to 2 labels

---

kolibri_explore_plugin/assets/src/views/SearchPage.vue

Add a callback to the "node updated" signal and change the corresponding array. For that Vue.$set has to be used so the app reacts to the change.
Fixes part of #625

Search: Refresh card after downloading

---

kolibri_explore_plugin/assets/src/kolibriApi.js
packages/template-ui/src/components/FilterResult.vue
packages/template-ui/src/mixins/updateNodeMixin.js
packages/template-ui/src/views/Content.vue
packages/template-ui/src/views/Home.vue
packages/template-ui/src/views/ListSection.vue
packages/template-ui/src/views/Search.vue
packages/template-ui/src/views/Section.vue

Update nodes template

---

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
kolibri_explore_plugin/assets/src/views/ContentUnavailablePage.vue
kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue
kolibri_explore_plugin/assets/src/views/DownloadPage.vue

Fix loading

---

kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue

As per new design request.
Resolves #660

Collections page: use default cards per row

---

packages/ek-components/src/styles.scss
packages/template-ui/src/components/ChannelHeader.vue

Various spacing and colour tweaks for channel pages based on feedback from @jofilizola.

Channel design tweaks

---

kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue

Feedback button visual adjustments

---

kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue
kolibri_explore_plugin/assets/src/views/SearchPage.vue
packages/ek-components/src/components/EkChannelCard.vue
packages/welcome-screen/src/views/PackSelection.vue

See commits
Closes https://github.com/endlessm/kolibri-explore-plugin/issues/671

Channel card updates

---

kolibri_explore_plugin/assets/src/views/DiscoveryPageContenPacks.vue
packages/ek-components/src/components/EkCardGrid.vue
packages/ek-components/src/components/EkCardGridPlaceholder.vue

These margins and paddings are making Joana sad. Nobody likes sad Joana, so let's fix these margins and paddings.
| Before | After |
|-----|-----|
| ![image](https://github.com/endlessm/kolibri-explore-plugin/assets/3518204/730ce0ed-9993-461a-a591-9c57a5fea88f) | ![image](https://github.com/endlessm/kolibri-explore-plugin/assets/3518204/a42091cf-566a-4bdf-983f-7d366a3e284d) |
https://github.com/endlessm/kolibri-explore-plugin/issues/679

Improve spacing of Featured Channels section

---

packages/ek-components/src/components/EkClamp.vue

Channel header: Safeguard empty description

---

packages/ek-components/src/components/EkCardButtons.vue
packages/ek-components/src/components/EkContentCard.vue
packages/ek-components/src/components/EkPlayButton.vue
packages/ek-components/src/main.js
packages/ek-components/src/styles.scss

Closes https://github.com/endlessm/kolibri-explore-plugin/issues/684

Add labels and hover feedback for content download buttons

---

packages/ek-components/src/components/EkCardButtons.vue

Closes https://github.com/endlessm/kolibri-explore-plugin/issues/690

Fix margins around content card download buttons

---

.github/workflows/main.yml
.gitignore
Pipfile
Pipfile.lock
README.md
kolibri_explore_plugin/fixtures/test-content.json
kolibri_explore_plugin/test/README.md
kolibri_explore_plugin/test/conftest.py
kolibri_explore_plugin/test/plugin.py
kolibri_explore_plugin/test/settings.py
kolibri_explore_plugin/test/test_models.py
package.json
pyproject.toml

This contains the infrastructure and a couple initial tests for testing the python backend with `pytest`. The added tests aren't especially useful, but they're included as a starting point. A bit more infrastructure will be needed to test the collection downloader and views. I have some of this locally, but it's messy. I'm hoping to get in this initial portion first.
Helps: #743

Python backend testing

---

packages/template-ui/channel-overrides/phet-interactive-simulations/styles.scss

https://github.com/endlessm/kolibri-explore-plugin/issues/712

PhET Simulations: Adjust header color

---

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
kolibri_explore_plugin/assets/src/routes/index.js

786 spanish pack

---

kolibri_explore_plugin/assets/src/kolibriApi.js
kolibri_explore_plugin/assets/src/views/SearchPage.vue
kolibri_explore_plugin/assets/src/views/welcome/PackSelectionPage.vue
packages/ek-components/package.json
packages/ek-components/src/components/EkPlayButton.vue
packages/ek-components/src/constants.js
packages/ek-components/src/utils.js
packages/template-ui/src/components/FilterContent.vue
packages/template-ui/src/store/modules/filters.js

This adds the missing translation calls to ek-components.
Fixes: #771

Add translation calls to ek-components

---

kolibri_explore_plugin/assets/src/views/ContentModal.vue

As per design request.
Fixes #828

Content modal: Prevent right click

---

kolibri_explore_plugin/locale/es_419/LC_MESSAGES/kolibri_explore_plugin.app-messages.json
kolibri_explore_plugin/locale/es_ES/LC_MESSAGES/kolibri_explore_plugin.app-messages.json

Spanish translation: Fix typo

---

kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
kolibri_explore_plugin/collectionviews.py

851 add spanish pack backend

---

kolibri_explore_plugin/assets/src/components/DiscoveryNavBar.vue
packages/ek-components/src/components/EkPlayButton.vue
packages/ek-components/src/styles.scss

725 fix get button

---

kolibri_explore_plugin/collectionviews.py

Group the manifest files in EN and ES. Then when extra metadata is imported, use the manifest for the corresponding group.
Helps #891

Collections backend: Import extra metadata per language
